/* UI only: inspection, collection and one short discovery stamp. */
(function(root){'use strict';
function create(api){const D=GameDepth,$=s=>document.querySelector(s),node=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
 const key='roguelette-collection-v2';let collection={chips:[],relics:[],synergies:[],pockets:[],bosses:[],challenges:[],tools:[],mutations:[]};try{const saved=JSON.parse(localStorage.getItem(key));for(const k of Object.keys(collection))if(Array.isArray(saved?.[k]))collection[k]=saved[k].filter(v=>typeof v==='string'&&v.length<100).slice(0,200);}catch{}
 const save=()=>{try{localStorage.setItem(key,JSON.stringify(collection));}catch{}};
 const wheelButton=node('button','RAD ANSEHEN ↗','text-button');wheelButton.id='inspect-wheel';wheelButton.setAttribute('aria-label','Radfelder und ihre Markierungen ansehen');$('.wheel-panel').append(wheelButton);
 const dialog=node('dialog',null,'depth-inspector ticket');dialog.id='depth-wheel';dialog.setAttribute('aria-label','Dein Rad');document.body.append(dialog);
 wheelButton.onclick=()=>{const s=api.getState();dialog.replaceChildren(node('h2','DEINE MASCHINE'),node('p',s.wheel.length+' Felder · jedes Feld gleich wahrscheinlich. Markierungen gelten nur für den aktuellen Run.'));const summary=api.wheelSummary(s.wheel),overview=node('section',null,'wheel-overview');overview.append(node('strong',summary.total+' Felder · '+summary.unique+' verschiedene Zahlen'),node('p','Häufigste Zahlen: '+summary.top.map(([n,count])=>n+' ('+count+'/'+summary.total+')').join(' · ')),node('p',summary.colors.map(c=>c.color+': '+c.count+'/'+summary.total).join(' · ')),node('p',Object.entries(summary.marks).filter(([,count])=>count).map(([m,count])=>m+': '+count+'/'+summary.total).join(' · ')||'Keine Markierungen'));for(const hint of api.wheelBuildHints(s))overview.append(node('p',hint));dialog.append(overview);const grid=node('div',null,'pocket-grid');s.wheel.forEach((f,i)=>{const card=node('article',null,'pocket-card '+f.color);card.append(node('strong',(i+1)+' · '+f.number),node('span',({red:'ROT',black:'SCHWARZ',green:'GRÜN'}[f.color])));if(f.mark){const def=D.pockets[f.mark];card.append(node('b',def.symbol+' '+def.label),node('p',def.description));if(f.mark==='Hot')card.append(node('small','Hitze der Zahl: '+(s.depth.room.numbers[f.number]||0)));}else card.append(node('small','Ohne Markierung'));if(s.bossWheel&&i>=s.bossWheel.length)card.append(node('small','Temporäres Bossfeld'));grid.append(card);});dialog.append(grid);const close=node('button','ZURÜCK','quiet');close.onclick=()=>dialog.close();dialog.append(close);dialog.showModal();};
 const rule=node('button','','text-button');rule.id='table-rule';rule.hidden=true;rule.onclick=()=>{const d=D.rules[api.room().rule];if(!d)return;dialog.replaceChildren(node('h2',d.name),node('p',d.description));const close=node('button','ZURÜCK','quiet');close.onclick=()=>dialog.close();dialog.append(close);dialog.showModal();};$('.bets-panel .section-heading').append(rule);
 const discovery=node('div',null,'synergy-discovery ticket');discovery.hidden=true;discovery.setAttribute('role','status');document.body.append(discovery);let timer,signature='',pendingDiscoveries=[];document.addEventListener('click',()=>queueMicrotask(update));
 const collectionArea=node('section',null,'depth-collection');$('#collection-dialog').append(collectionArea);
 function renderCollection(){collectionArea.replaceChildren(node('h3','ENTDECKUNGEN'));const groups={chips:api.chips.map(c=>c.name),relics:Object.keys(api.relics),synergies:api.allSynergies().map(s=>s.name),pockets:Object.keys(D.pockets),tools:Object.keys(api.tools),mutations:Object.keys(api.mutations),bosses:['Double Zero','The Taxman','The Minimalist','The House'],challenges:D.challenges.map(c=>c.id)};const titles={chips:'Chips',relics:'Relics',synergies:'Synergien',pockets:'Feldmarkierungen',tools:'Rad-Werkzeuge',mutations:'Mutationen',bosses:'Bosse besiegt',challenges:'Herausforderungen'};
  for(const [kind,all]of Object.entries(groups)){const details=node('details'),summary=node('summary',titles[kind]+' · '+all.filter(x=>collection[kind].includes(x)).length+' / '+all.length);details.append(summary);const list=node('ul');for(const name of all){const li=node('li');if(!collection[kind].includes(name)){li.textContent='???';list.append(li);continue;}const def=kind==='chips'?api.entries.find(c=>c.type==='chip'&&c.name===name):kind==='relics'?api.entries.find(c=>c.type==='relic'&&c.name===name):kind==='synergies'?api.allSynergies().find(c=>c.name===name):kind==='pockets'?D.pockets[name]:kind==='tools'?api.tools[name]:kind==='mutations'?api.mutations[name]:kind==='challenges'?D.challenges.find(c=>c.id===name):null;li.append(node('strong',def?.name||name));if(def){li.append(node('p',def.effect||def.description));const tags=D.itemTags({name,...def});li.append(node('small',[def.rarity,tags.map(t=>D.tags[t]||t).join(' · '),def.unlock?'Freischaltung: '+(api.achievements.find(c=>c.id===def.unlock)?.description||def.unlock):''].filter(Boolean).join(' · ')));if(kind==='synergies')li.append(node('p',(def.bonusType==='bonus'?'SONDERBONUS':'ZUSAMMENSPIEL · kein Namensbonus')+' · '+def.reason));else{const related=api.allSynergies().filter(c=>(c.sources||[]).includes(name));if(related.length)li.append(node('small','Verbindungen: '+related.map(c=>c.name).join(' · ')));}}list.append(li);}details.append(list);collectionArea.append(details);}
  const s=api.getState();collectionArea.append(node('p','Im aktuellen Run: Nullschleife '+Math.min(3,s.depth.run.zeros)+' / 3 · Graviermeister '+Math.min(5,s.depth.run.mods)+' / 5'));
 }
 $('#open-collection').addEventListener('click',renderCollection);
 const buildExtras=node('section',null,'build-wheel-summary');$('#build-dialog').append(buildExtras);
 $('#edit-build').addEventListener('click',()=>{const s=api.getState();buildExtras.replaceChildren(node('h3','RAD & RELICS'));buildExtras.append(node('p',(s.bossWheel||s.wheel).filter(f=>f.mark).length+' markierte Felder · '+new Set(s.wheel.map(f=>f.number)).size+' verschiedene Zahlen'));for(const [mark,d]of Object.entries(D.pockets)){const n=(s.bossWheel||s.wheel).filter(f=>f.mark===mark).length;if(n)buildExtras.append(node('p',d.symbol+' '+d.label+' ×'+n+' · '+d.description));}s.relics.forEach(r=>buildExtras.append(node('p',r.name+' · '+api.relics[r.name].description)));});
 const table=$('.game-layout'),ruleSymbols={precision:'⌖',parity:'Ⅱ',range:'↔',color:'◆',heat:'♨',toll:'◈',narrow:'••',spread:'▤'};
 function update(){const s=api.getState();if(s.discoveries)for(const k of Object.keys(collection))if(Array.isArray(s.discoveries[k]))collection[k]=[...new Set([...collection[k],...s.discoveries[k].filter(v=>typeof v==='string')])];wheelButton.disabled=s.phase==='spinning';const ruleId=api.room()?.rule;const r=D.rules[ruleId];const visible=!!r&&api.started()&&!table.classList.contains('boss-active');
  if(visible){table.dataset.tableRule=ruleId;document.documentElement.dataset.tableRule=ruleId;}else{delete table.dataset.tableRule;delete document.documentElement.dataset.tableRule;}
  rule.hidden=!visible;rule.textContent=r?ruleSymbols[ruleId]+' '+r.name+' ⓘ':'';rule.title=r?.description||'';rule.setAttribute('aria-label',r?'Aktive Tischregel: '+r.name+'. '+r.description:'Tischregel');
  if(!api.started()||s.phase==='spinning')return;const active=api.synergies(),current={chips:s.chips.map(c=>c.name),relics:s.relics.map(r=>r.name),synergies:active.map(x=>x.name),pockets:s.wheel.map(f=>f.mark).filter(Boolean),tools:s.items.map(i=>i.name),mutations:s.chips.flatMap(c=>c.mutations),bosses:s.map.flat().filter(n=>n.type==='boss'&&(s.cleared.includes(n.id)||s.phase==='won'&&s.currentRoom===n.id)).map(n=>n.name),challenges:api.challenges().filter(id=>id.startsWith('depth-'))};const fresh=active.filter(x=>!collection.synergies.includes(x.name));for(const k of Object.keys(collection))collection[k]=[...new Set([...collection[k],...current[k]])];const next=JSON.stringify(collection);if(next!==signature){signature=next;save();}if(api.started()&&JSON.stringify(s.discoveries)!==next){s.discoveries=JSON.parse(next);api.persist?.();}
  for(const item of fresh)if(!pendingDiscoveries.some(x=>x.id===item.id))pendingDiscoveries.push(item);
  if(pendingDiscoveries.length&&!document.querySelector('dialog[open]')){const fresh=pendingDiscoveries.splice(0);clearTimeout(timer);discovery.replaceChildren(node('strong',fresh[0].bonusType==='bonus'?'SONDERBONUS ENTDECKT':'ZUSAMMENSPIEL ENTDECKT'),node('span',fresh.map(x=>x.name).join(' · ')),node('small',(fresh[0].sources?.join(' + ')||fresh[0].reason)+' · '+fresh[0].description));discovery.title=fresh.map(x=>x.reason+' — '+x.description).join('\n');discovery.hidden=false;timer=setTimeout(()=>discovery.hidden=true,2400);}
 }
 return {update};}
root.DepthUI={create};})(globalThis);
