/* UI only: inspection, collection and one short discovery stamp. */
(function(root){'use strict';
function create(api){const D=GameDepth,$=s=>document.querySelector(s),node=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
 const key='roguelette-collection-v2';let collection={chips:[],relics:[],synergies:[],pockets:[],bosses:[],challenges:[]};try{const saved=JSON.parse(localStorage.getItem(key));for(const k of Object.keys(collection))if(Array.isArray(saved?.[k]))collection[k]=saved[k].filter(v=>typeof v==='string'&&v.length<100).slice(0,200);}catch{}
 const save=()=>{try{localStorage.setItem(key,JSON.stringify(collection));}catch{}};
 const wheelButton=node('button','RAD ANSEHEN ↗','text-button');wheelButton.id='inspect-wheel';wheelButton.setAttribute('aria-label','Radfelder und ihre Markierungen ansehen');$('.wheel-panel').append(wheelButton);
 const dialog=node('dialog',null,'depth-inspector ticket');dialog.id='depth-wheel';dialog.setAttribute('aria-label','Dein Rad');document.body.append(dialog);
 wheelButton.onclick=()=>{const s=api.getState();dialog.replaceChildren(node('h2','DEINE MASCHINE'),node('p',s.wheel.length+' Felder · jedes Feld gleich wahrscheinlich. Markierungen gelten nur für den aktuellen Run.'));const grid=node('div',null,'pocket-grid');s.wheel.forEach((f,i)=>{const card=node('article',null,'pocket-card '+f.color);card.append(node('strong',(i+1)+' · '+f.number),node('span',({red:'ROT',black:'SCHWARZ',green:'GRÜN'}[f.color])));if(f.mark){const def=D.pockets[f.mark];card.append(node('b',def.symbol+' '+def.label),node('p',def.description));if(f.mark==='Hot')card.append(node('small','Bisherige Feldtreffer: '+(s.depth.room.heat[i]||0)));}else card.append(node('small','Ohne Markierung'));if(s.bossWheel&&i>=s.bossWheel.length)card.append(node('small','Temporäres Bossfeld'));grid.append(card);});dialog.append(grid);const close=node('button','ZURÜCK','quiet');close.onclick=()=>dialog.close();dialog.append(close);dialog.showModal();};
 const rule=node('button','','text-button');rule.id='table-rule';rule.hidden=true;rule.onclick=()=>{const d=D.rules[api.room().rule];if(!d)return;dialog.replaceChildren(node('h2',d.name),node('p',d.description));const close=node('button','ZURÜCK','quiet');close.onclick=()=>dialog.close();dialog.append(close);dialog.showModal();};$('.bets-panel .section-heading').append(rule);
 const discovery=node('div',null,'synergy-discovery ticket');discovery.hidden=true;discovery.setAttribute('role','status');document.body.append(discovery);let timer,signature='';
 const collectionArea=node('section',null,'depth-collection');$('#collection-dialog').append(collectionArea);
 function renderCollection(){collectionArea.replaceChildren(node('h3','ENTDECKUNGEN'));const groups={chips:api.chips.map(c=>c.name),relics:Object.keys(api.relics),synergies:api.allSynergies().map(s=>s.name),pockets:Object.keys(D.pockets),bosses:['Double Zero','The Taxman','The Minimalist','The House'],challenges:D.challenges.map(c=>c.id)};const titles={chips:'Chips',relics:'Relics',synergies:'Synergien',pockets:'Feldmarkierungen',bosses:'Bosse besiegt',challenges:'Herausforderungen'};
  for(const [kind,all]of Object.entries(groups)){// Include known old named synergies even when this build is inactive.
   if(kind==='synergies')all.splice(0,all.length,...new Set([...all,...collection.synergies]));const details=node('details'),summary=node('summary',titles[kind]+' · '+all.filter(x=>collection[kind].includes(x)).length+' / '+all.length);details.append(summary);const list=node('ul');all.forEach(name=>list.append(node('li',collection[kind].includes(name)?kind==='challenges'?D.challenges.find(c=>c.id===name)?.name||name:name:'???')));details.append(list);collectionArea.append(details);}
 }
 $('#open-collection').addEventListener('click',renderCollection);
 const buildExtras=node('section',null,'build-wheel-summary');$('#build-dialog').append(buildExtras);
 $('#edit-build').addEventListener('click',()=>{const s=api.getState();buildExtras.replaceChildren(node('h3','RAD & RELICS'));buildExtras.append(node('p',(s.bossWheel||s.wheel).filter(f=>f.mark).length+' markierte Felder · '+new Set(s.wheel.map(f=>f.number)).size+' verschiedene Zahlen'));for(const [mark,d]of Object.entries(D.pockets)){const n=(s.bossWheel||s.wheel).filter(f=>f.mark===mark).length;if(n)buildExtras.append(node('p',d.symbol+' '+d.label+' ×'+n+' · '+d.description));}s.relics.forEach(r=>buildExtras.append(node('p',r.name+' · '+api.relics[r.name].description)));});
 function update(){const s=api.getState();wheelButton.disabled=s.phase==='spinning';const r=D.rules[api.room()?.rule];rule.hidden=!r;rule.textContent=r?r.name+' ⓘ':'';rule.title=r?.description||'';
  if(!api.started()||s.phase==='spinning')return;const active=api.synergies(),current={chips:s.chips.map(c=>c.name),relics:s.relics.map(r=>r.name),synergies:active.map(x=>x.name),pockets:s.wheel.map(f=>f.mark).filter(Boolean),bosses:s.map.flat().filter(n=>n.type==='boss'&&(s.cleared.includes(n.id)||s.phase==='won'&&s.currentRoom===n.id)).map(n=>n.name),challenges:api.challenges().filter(id=>id.startsWith('depth-'))};const fresh=active.filter(x=>!collection.synergies.includes(x.name));for(const k of Object.keys(collection))collection[k]=[...new Set([...collection[k],...current[k]])];const next=JSON.stringify(collection);if(next!==signature){signature=next;save();}
  if(fresh.length){clearTimeout(timer);discovery.replaceChildren(node('strong','SYNERGIE ENTDECKT'),node('span',fresh.map(x=>x.name).join(' · ')),node('small',(fresh[0].sources?.join(' + ')||fresh[0].reason)+' · '+fresh[0].description));discovery.title=fresh.map(x=>x.reason+' — '+x.description).join('\n');discovery.hidden=false;timer=setTimeout(()=>discovery.hidden=true,2400);}
 }
 return {update};}
root.DepthUI={create};})(globalThis);
