const passDetour=require('./route.fixture.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),g=require('../script.js');
function state(names=['Basic']){const s=g.createState(()=>0);s.chips=names.map((name,id)=>g.createChip(g.CHIP_CATALOG.find(c=>c.name===name),id));s.nextChipId=names.length;g.updateBuildStats(s);return s;}
function relics(s,...names){s.relics=names.map((name,id)=>({id,name}));s.nextRelicId=names.length;}
function spin(s,result={number:1,color:'red'},random=()=>1){assert(g.startSpin(s));assert(g.resolveSpin(s,result,random));return s.spinScore;}
function roundtrip(s){const d=g.decodeRun(g.encodeRun(s,null,null));assert(d.ok,JSON.stringify(d));return d.state;}
function event(id,names=['Basic']){const s=state(names);s.phase='event';s.eventId=id;s.mapStep=3;s.currentRoom='unknown';s.visited=['entry','table-2','shop','unknown'];s.coins=30;return s;}
function atomic(s,fn){const before=JSON.stringify(s);assert(!fn().ok);assert.equal(JSON.stringify(s),before);}
const active=s=>g.activeSynergies(s).map(x=>x.id);
test('Basic remains clean; synergies cannot activate from a single component',()=>{const s=state();assert.equal(s.chips[0].curse,null);assert.deepEqual(s.chips[0].mutations,[]);assert.deepEqual(active(s),[]);relics(s,...Object.keys(g.RELIC_TYPES).slice(0,4));assert.deepEqual(active(s),[]);});
test('Red synergy requires a real red majority and pays only once per qualifying spin',()=>{const s=state(['Crimson','Ember']);relics(s,'Blood Pact');assert(!active(s).includes('red'));s.wheel[2].color='red';assert(active(s).includes('red'));s.chips.forEach(c=>g.placeBet(s,c.id,'outside','red'));spin(s);assert.equal(s.coins,7);assert.equal(s.synergyTrace.length,1);});
test('Precision and Echo share one bounded retrigger; Lucky Seven never rerolls it',()=>{const s=state(['Sniper','Basic']);relics(s,'Bullseye','Lucky Seven');s.wheel.push({number:7,color:'red'});s.chips[0].mutations=['Echo'];g.placeBet(s,0,'number',7);let calls=0;spin(s,{number:7,color:'red'},()=>{calls++;return .3;});assert.equal(calls,1);assert.equal(s.breakdown[0].points,600);assert.equal(s.spinScore,1350);assert(s.synergyTrace.some(t=>t.includes('Präzision')));});
test('Resonance raises Echo to 40 percent without creating recursive hits',()=>{const s=state(['Basic','Basic']);s.chips.forEach(c=>c.mutations=['Echo']);relics(s,'Lucky Seven');assert(active(s).includes('echo'));g.placeBet(s,0,'number',7);let calls=0;assert.equal(spin(s,{number:7,color:'red'},()=>{calls++;return .3;}),300);assert.equal(calls,1);});
test('Zero synergy counts permanent zeros only and requires the Zero chip to hit',()=>{const s=state(['Zero']);relics(s,'Green Seal');s.bossWheel=s.wheel.map(f=>({...f}));s.wheel.push({number:0,color:'green'},{number:0,color:'green'});assert(!active(s).includes('zero'));s.bossWheel=null;assert(active(s).includes('zero'));g.placeBet(s,0,'number',0);assert.equal(spin(s,{number:0,color:'green'}),1200);assert.equal(s.lastSpin.zeroMultiplier,1);const b=state(['Zero','Basic']);b.wheel.push({number:0,color:'green'},{number:0,color:'green'});relics(b,'Green Seal');g.placeBet(b,1,'number',0);assert.equal(spin(b,{number:0,color:'green'}),150);});
test('Streak guard works once per table, persists through saves and resets on table entry',()=>{const s=state(['Streak']);relics(s,'Safety Net');s.wheel.filter(f=>f.number>0).forEach(f=>f.color='red');s.chips[0].streak=5;g.placeBet(s,0,'number',2);spin(s);assert.equal(s.chips[0].streak,3);let d=roundtrip(s);spin(d);assert.equal(d.chips[0].streak,0);d.phase='map';assert(g.enterRoom(d,'table-2',()=>0));assert.equal(d.streakGuardUsed,false);});
test('Coverage synergy lowers its requirement to three actual wager families',()=>{const s=state(['Balance','Anchor','Basic']);relics(s,'Full Coverage');g.placeBet(s,0,'outside','odd');g.placeBet(s,1,'outside','red');g.placeBet(s,2,'number',1);assert.equal(spin(s),255);assert(s.relicTrace[0].triggered);});
test('Polished, Cursed, Blood Pact score once in the established order',()=>{const s=state();s.chips[0].mutations=['Polished'];assert(g.grantCurse(s,0,'Cursed').ok);assert.equal(s.wheel.length,20);assert(!g.grantCurse(s,0,'Cursed').ok);assert.equal(s.wheel.length,20);relics(s,'Blood Pact');g.placeBet(s,0,'outside','red');assert.equal(spin(s),135);assert.match(s.breakdown[0].curseNote,/Cursed/);});
test('Greedy blocks uncommitted spins, including at Minimalist without impossible requirements',()=>{const s=state(['Basic','Basic','Basic','Basic']);s.chips.forEach(c=>g.grantCurse(s,c.id,'Greedy'));g.placeBet(s,0,'outside','red');assert(!g.startSpin(s));assert.equal(s.spinsLeft,5);s.floor=3;s.map=g.createFloorMap(3,()=>0);s.currentRoom='f3-boss';s.mapStep=5;s.target=700;g.placeBet(s,1,'outside','red');g.placeBet(s,2,'outside','red');assert.equal(g.missingGreedy(s).length,0);assert(!g.placeBet(s,3,'outside','red'));assert(g.startSpin(s));});
test('Fragile breaks on third loss, removes stale bets and rescues an empty build with clean Basic',()=>{const s=state();g.grantCurse(s,0,'Fragile');g.placeBet(s,0,'number',2);spin(s);spin(s);assert.equal(s.chips[0].curse.losses,2);const d=roundtrip(s);spin(d);assert.equal(d.chips.length,1);assert.equal(d.chips[0].curse,null);assert.equal(d.chips[0].name,'Basic');assert.equal(d.placedBets.length,0);assert(d.synergyTrace.some(x=>x.includes('zerbrochen')));});
test('Fragile ignores unplaced spins and winning spins do not heal loss count',()=>{const s=state(['Basic','Basic']);g.grantCurse(s,0,'Fragile');g.placeBet(s,1,'number',2);spin(s);assert.equal(s.chips[0].curse.losses,0);g.placeBet(s,0,'number',1);s.chips[0].curse.losses=2;spin(s);assert.equal(s.chips[0].curse.losses,2);});
test('Addicted remembers wager family across reload and penalizes family switches',()=>{const s=state();g.grantCurse(s,0,'Addicted');g.placeBet(s,0,'number',2);spin(s);const d=roundtrip(s);g.placeBet(d,0,'number',1);assert.equal(spin(d),150);const b=state();g.grantCurse(b,0,'Addicted');b.chips[0].curse.lastFamily='number';g.placeBet(b,0,'outside','red');assert.equal(spin(b),10);});
test('Volatile rolls only on a hit, applies loss after relics and cannot make score negative',()=>{const s=state(['Basic','Basic']);g.grantCurse(s,0,'Volatile');relics(s,'Blood Pact');g.placeBet(s,0,'number',2);g.placeBet(s,1,'outside','red');assert.equal(spin(s),20);assert.equal(s.lastSpin.cursePenalty,10);const b=state();g.grantCurse(b,0,'Volatile');g.placeBet(b,0,'number',2);assert.equal(spin(b),0);assert.equal(b.lastSpin.cursePenalty,0);const c=state();g.grantCurse(c,0,'Volatile');g.placeBet(c,0,'number',1);assert.equal(spin(c,undefined,()=>.34),300);});
test('Heavy and Expanded maintain capacity through token grants and explicit replacement',()=>{const s=state(Array(6).fill('Basic'));atomic(s,()=>g.grantCurse(s,0,'Heavy'));s.chips[0].mutations=['Expanded'];assert(g.grantCurse(s,0,'Heavy').ok);assert.equal(g.chipLoad(s),7);assert.equal(g.chipCapacity(s),7);s.phase='slot';s.pendingToken={type:'chip',name:'Basic',rarity:'Common',rolledRarity:'Common',mutations:[],returnPhase:'ready'};atomic(s,()=>g.claimToken(s));assert(g.claimToken(s,0).ok);assert.equal(g.chipLoad(s),6);assert.equal(g.chipCapacity(s),6);});
test('Ten new event rooms each offer a free exit with full inventories',()=>{assert.equal(g.BUILD_EVENTS.length,18);for(const e of g.BUILD_EVENTS){const s=event(e.id,Array(6).fill('Basic'));relics(s,'Blood Pact','Bullseye','Crown','Green Seal');const r=g.resolveRoom(s,'leave');assert(r.ok,e.id);assert.equal(s.phase,'map');roundtrip(s);assert(!g.resolveRoom(s,'leave').ok);}});
test('Altar trades three exact fields and requires explicit replacement at four relics',()=>{const s=event('altar');relics(s,'Blood Pact','Bullseye','Green Seal','Safety Net');atomic(s,()=>g.resolveBuildEvent(s,'trade'));assert(g.resolveBuildEvent(s,'trade',{relicId:1}).ok);assert.equal(s.wheel.length,16);assert.equal(s.relics.length,4);assert(s.relics.some(r=>r.name==='Crown'));assert(!s.relics.some(r=>r.name==='Bullseye'));roundtrip(s);const b=event('altar');b.wheel=b.wheel.slice(0,8);atomic(b,()=>g.resolveBuildEvent(b,'trade'));});
test('Red dye changes at most three black fields and consumes one permanent wheel slot',()=>{const s=event('red-dye');assert(g.resolveBuildEvent(s,'paint').ok);assert.equal(s.wheel.filter(f=>f.color==='red').length,12);assert.equal(s.wheel.filter(f=>f.number===0).length,2);assert.equal(s.wheel.length,20);roundtrip(s);});
test('Chip sacrifice respects full/Expanded inventory and never removes the sole chip on failure',()=>{const s=event('twins',Array(6).fill('Basic'));atomic(s,()=>g.resolveBuildEvent(s,'trade',{chipId:0}));const b=event('twins');assert(g.resolveBuildEvent(b,'trade',{chipId:0},()=>0).ok);assert.equal(b.chips.length,2);assert(b.chips.every(c=>c.id!==0&&!c.curse));roundtrip(b);});
test('Double seal adds two distinct mutations and only one curse; no repeated event grant',()=>{for(const curse of Object.keys(g.CURSES)){const s=event('brand');assert(g.resolveBuildEvent(s,curse,{chipId:0},()=>0).ok);assert.equal(s.chips[0].mutations.length,2);assert.equal(new Set(s.chips[0].mutations).size,2);assert.equal(s.chips[0].curse.name,curse);roundtrip(s);atomic(s,()=>g.resolveBuildEvent(s,curse,{chipId:0}));}});
test('Pawn cash/luck branches remove only the selected relic and persist',()=>{for(const choice of ['cash','luck']){const s=event('pawn');relics(s,'Blood Pact','Safety Net');assert(g.resolveBuildEvent(s,choice,{relicId:1}).ok);assert.deepEqual(s.relics.map(r=>r.name),['Blood Pact']);const d=roundtrip(s);assert.equal(d.coins,choice==='cash'?48:30);assert.equal(d.luck,choice==='luck'?1:0);}});
test('Mutation washing respects Expanded capacity, replaces rather than duplicates and charges once',()=>{const s=event('wash');s.chips[0].mutations=['Lucky'];assert(g.resolveBuildEvent(s,'wash',{chipId:0,mutation:'Lucky'},()=>0).ok);assert.deepEqual(s.chips[0].mutations,['Polished']);assert.equal(s.coins,27);const b=event('wash',Array(7).fill('Basic'));b.chips[0].mutations=['Expanded'];atomic(b,()=>g.resolveBuildEvent(b,'wash',{chipId:0,mutation:'Expanded'},()=>0));});
test('Borrowed spin debt applies once on next combat and persists across shop/save',()=>{const s=event('borrow');assert(g.resolveBuildEvent(s,'double',{fieldIndex:1}).ok);let d=roundtrip(s);assert.equal(d.nextTableSpinDebt,1);assert((passDetour(d),g.enterRoom(d,'final-shop',()=>0)));g.resolveRoom(d,'leave');assert(g.enterRoom(d,'boss',()=>0));assert.equal(d.spinsLeft,6);assert.equal(d.nextTableSpinDebt,0);roundtrip(d);});
test('Floor boon activates only next floor and expires before the floor after, including Endless',()=>{const s=event('boon');assert(g.resolveBuildEvent(s,'buy').ok);assert.equal(s.luck,0);assert.equal(s.coins,18);let d=roundtrip(s);d.phase='floor-clear';assert(g.advanceFloor(d,()=>0));assert.equal(d.luck,3);assert.equal(d.spinsLeft,g.currentRoom(d).spins-1);d.phase='floor-clear';assert(g.advanceFloor(d,()=>0));assert.equal(d.luck,0);assert.equal(d.floorBoon,null);const e=state();e.floor=4;e.map=g.createFloorMap(4,()=>0);e.currentRoom='f4-boss';e.phase='complete';e.normalWon=true;e.floorBoon={floor:5};g.grantCurse(e,0,'Addicted');assert(g.continueEndless(e,()=>0));assert.equal(e.chips[0].curse.name,'Addicted');assert.equal(e.luck,3);});
test('Curse removal keeps Cursed zero; sacrificing Expanded cannot overfill inventory',()=>{const s=event('purge');g.grantCurse(s,0,'Cursed');assert(g.resolveBuildEvent(s,'pay',{chipId:0}).ok);assert.equal(s.chips[0].curse,null);assert.equal(s.wheel.length,20);assert.equal(s.coins,20);const b=event('purge',Array(7).fill('Basic'));b.chips[0].mutations=['Expanded'];g.grantCurse(b,0,'Greedy');atomic(b,()=>g.resolveBuildEvent(b,'mutation',{chipId:0,mutation:'Expanded'}));});
test('Forge gives the selected mutation/curse and is atomic on low funds or no free Heavy slot',()=>{for(const choice of ['heavy','greedy']){const s=event('forge');assert(g.resolveBuildEvent(s,choice,{chipId:0}).ok);assert.equal(s.chips[0].curse.name,choice==='heavy'?'Heavy':'Greedy');roundtrip(s);}const b=event('forge',Array(6).fill('Basic'));atomic(b,()=>g.resolveBuildEvent(b,'heavy',{chipId:0}));b.coins=0;atomic(b,()=>g.resolveBuildEvent(b,'greedy',{chipId:0}));});
test('Save validates curse data, preserves active synergy and migrates old version-1 fields',()=>{const s=state(['Zero']);relics(s,'Green Seal');s.wheel.push({number:0,color:'green'});g.grantCurse(s,0,'Cursed');const d=roundtrip(s);assert(active(d).includes('zero'));assert.equal(d.chips[0].curse.name,'Cursed');const data=JSON.parse(g.encodeRun(s,null,null));data.state.chips[0].curse.losses=-1;assert(!g.decodeRun(JSON.stringify(data)).ok);const old=JSON.parse(g.encodeRun(state(),null,null));for(const key of ['bonusLuck','nextTableSpinDebt','floorBoon','streakGuardUsed','lastEvent','synergyTrace'])delete old.state[key];delete old.state.chips[0].curse;assert(g.decodeRun(JSON.stringify(old)).ok);});
