const {test}=require('node:test'),assert=require('node:assert/strict'),g=require('../script.js');
function state(names){const s=g.createState(()=>0);s.chips=names.map((n,id)=>g.createChip(g.CHIP_CATALOG.find(c=>c.name===n),id));s.nextChipId=names.length;s.target=99999;return s;}
function spin(s,result){assert(g.startSpin(s));assert(g.resolveSpin(s,result,()=>.99));}
function load(s){const d=g.decodeRun(g.encodeRun(s,null,null));assert(d.ok);return d.state;}
const red={number:1,color:'red'},black={number:2,color:'black'};
test('Drifter and Metronome reward a real color switch; first spin, zero and misses do not',()=>{const s=state(['Drifter']);s.relics=[{id:0,name:'Metronome'}];g.placeBet(s,0,'outside','red');spin(s,red);assert.equal(s.spinScore,20);g.placeBet(s,0,'outside','black');spin(s,black);assert.equal(s.spinScore,65);spin(s,{number:0,color:'green'});assert.equal(s.spinScore,0);spin(s,black);assert.equal(s.spinScore,20);});
test('Collector counts empty capacity including Heavy/Expanded and has a strict cap',()=>{const s=state(['Collector']),bet={chip:s.chips[0],type:'outside',value:'red'};assert.equal(g.calculateBetScore(bet,{state:s}),36);s.chips.push(...Array.from({length:4},(_,i)=>g.createChip(g.CHIP_TYPES[0],i+1)));assert.equal(g.calculateBetScore(bet,{state:s}),24);g.grantCurse(s,1,'Heavy');assert.equal(g.calculateBetScore(bet,{state:s}),20);s.chips[1].mutations=['Expanded'];assert.equal(g.calculateBetScore(bet,{state:s}),24);assert.equal(g.calculateBetScore({...bet,type:'number',value:1},{state:s}),100);});
test('Surveyor and Compass count distinct winning families, not losing or duplicate bets',()=>{const s=state(['Surveyor','Basic','Basic','Basic']);s.relics=[{id:0,name:'Compass'}];for(const [id,type,value]of [[0,'outside','red'],[1,'outside','odd'],[2,'outside','odd'],[3,'outside','high']])g.placeBet(s,id,type,value);spin(s,red);assert.equal(s.breakdown[0].basePoints,30);assert.equal(s.spinScore,110);assert.match(s.relicTrace[0].effect,/2 gewinnende/);});
test('Carbon rewards permanent duplicates only and caps at four extra copies',()=>{const s=state(['Carbon']),bet={chip:s.chips[0],type:'number',value:1};assert.equal(g.calculateBetScore(bet,{state:s}),100);s.wheel.push(red,red);assert.equal(g.calculateBetScore(bet,{state:s}),300);s.wheel.push(...Array(8).fill(red));assert.equal(g.calculateBetScore(bet,{state:s}),500);s.bossWheel=[...s.wheel];s.wheel.push({number:0,color:'green'},{number:0,color:'green'});assert.equal(g.calculateBetScore({...bet,value:0},{state:s}),100);assert.equal(g.calculateBetScore({...bet,type:'outside',value:'red'},{state:s}),20);});
test('New flat bonuses enter Polished/Echo/Lucky Seven once, and relic order still matters',()=>{const s=state(['Drifter']);s.history=[black];s.chips[0].mutations=['Polished','Echo'];s.relics=[{id:0,name:'Lucky Seven'}];g.placeBet(s,0,'outside','red');g.startSpin(s);g.resolveSpin(s,{number:7,color:'red'},()=>0);assert.equal(s.breakdown[0].basePoints,60);assert.equal(s.spinScore,180);const c={result:red,previous:black,bets:1,winners:1};assert.equal(g.applyRelics([{name:'Metronome'},{name:'Blood Pact'}],c,20).score,67.5);assert.equal(g.applyRelics([{name:'Blood Pact'},{name:'Metronome'}],c,20).score,55);});
test('Afterimage requires a repeated number, Workshop Seal uses permanent size and both need winners',()=>{const c={result:red,previous:red,winners:1,wheelSize:12};assert.equal(g.applyRelics([{name:'Afterimage'},{name:'Workshop Seal'}],c,20).score,180);assert.equal(g.applyRelics([{name:'Afterimage'}],{...c,previous:{number:3,color:'red'}},20).score,20);assert.equal(g.applyRelics([{name:'Workshop Seal'}],{...c,wheelSize:13},20).score,20);assert.equal(g.applyRelics([{name:'Afterimage'},{name:'Workshop Seal'}],{...c,winners:0},0).score,0);const s=state(['Basic']);s.wheel=s.wheel.slice(0,12);s.bossWheel=[...s.wheel];s.wheel.push({number:0,color:'green'},{number:0,color:'green'});s.relics=[{id:0,name:'Workshop Seal'}];g.placeBet(s,0,'outside','red');spin(s,red);assert.equal(s.spinScore,80);});
test('New content and previous-spin conditions survive save/load with canonical bets',()=>{const s=state(['Drifter','Collector','Surveyor','Carbon']);s.relics=['Metronome','Afterimage','Compass','Workshop Seal'].map((name,id)=>({id,name}));s.nextRelicId=4;s.target=20;s.history=[black];g.placeBet(s,0,'outside','red');const d=load(s);assert.deepEqual(d.chips.map(c=>c.name),s.chips.map(c=>c.name));spin(d,red);assert.equal(d.spinScore,65);assert.deepEqual(load(d).lastSpin,d.lastSpin);});
test('V1.2 maps retain length, targets and payouts; advancing switches to V1.3',()=>{const s=g.createState(()=>0);s.mapVersion=2;s.map=g.versionTwoFloorMap(1,()=>0);const d=load(s);assert.equal(d.map.length,6);assert.deepEqual(d.map,s.map);d.phase='floor-clear';assert(g.advanceFloor(d,()=>0));assert.equal(d.mapVersion,3);assert.equal(d.map.length,7);assert.equal(load(d).map.length,7);});
test('Every floor gains exactly one tier with meaningful options and a guaranteed final shop',()=>{for(let f=1;f<=12;f++){const m=g.createFloorMap(f,()=>0),old=g.versionTwoFloorMap(f,()=>0);assert.equal(m.length,old.length+1);assert.deepEqual(new Set(m.at(-3).map(n=>n.type)),new Set(['workshop','event','table']));assert.equal(m.at(-2)[0].type,'shop');assert.equal(m.at(-1)[0].type,'boss');assert(m.at(-3).every(n=>n.next[0]===m.at(-2)[0].id));}assert.equal(g.createFloorMap(2,()=>0).at(-1)[0].target,320);assert.equal(g.createFloorMap(4,()=>0).at(-1)[0].target,850);});
test('Side workshop gives a precise free tool once, usable immediately and saved',()=>{const s=g.createState(()=>0);s.currentRoom='detour-workshop';s.mapStep=s.map.length-3;s.visited.push(s.currentRoom);s.phase='workshop';assert.deepEqual(g.workshopChoices(s),['Delete','Rewrite','Gild']);assert(!g.resolveRoom(s,'Mitosis').ok);assert(g.resolveRoom(s,'Delete').ok);assert(!g.resolveRoom(s,'Delete').ok);assert(g.useWheelItem(s,s.items[0].id,0).ok);assert.equal(load(s).wheel.length,18);});
