const test=require('node:test'),assert=require('node:assert/strict'),g=require('../script.js');
const rng=seed=>()=>((seed=(1664525*seed+1013904223)>>>0)/2**32);
function floor(n=2){const s=g.createState(rng(32));s.floor=n;s.map=g.createFloorMap(n,rng(44));const room=s.map.flat().find(r=>r.type==='table'&&!r.id.endsWith('entry'));Object.assign(s,{currentRoom:room.id,mapStep:s.map.findIndex(row=>row.includes(room)),visited:[room.id],target:room.target,spinsLeft:room.spins});return s;}
function victory(){const s=floor();s.score=s.target-1;g.placeBet(s,0,'outside','red');g.startSpin(s);g.resolveSpin(s,s.wheel[1],()=>.99,1);return s;}
function event(id){const s=g.createState(()=>0),room=s.map.flat().find(r=>r.type==='event');Object.assign(s,{phase:'event',eventId:id,currentRoom:room.id,mapStep:s.map.findIndex(row=>row.includes(room)),visited:[room.id],coins:30});return s;}
test('All four tokens guarantee their types, retain mixed weights, survive pending reload and require explicit replacements',()=>{for(const [name,type]of [['Chip Token','chip'],['Relic Token','relic'],['Rad Token','item'],['Slot Token','chip']]){const s=g.createState(()=>0);s.chips=Array.from({length:6},(_,id)=>g.createChip(g.CHIP_TYPES[0],id));s.nextChipId=6;s.relics=Object.keys(g.RELIC_TYPES).slice(0,4).map((name,id)=>({name,id}));s.nextRelicId=4;s.items=[{name:'Duplicate',id:0},{name:'Delete',id:1}];s.nextItemId=2;assert(g.grantToken(s,name));assert(g.beginToken(s,0,()=>.1).ok);assert.equal(s.pendingToken.type,type);const raw=g.encodeRun(s),restored=g.decodeRun(raw);assert(restored.ok);assert(!g.claimToken(s).ok);assert.equal(g.encodeRun(s).includes('pendingToken'),true);assert(g.claimToken(s,0).ok);assert.equal(s.phase,'ready');assert(!g.claimToken(s).ok);const other=restored.state,coins=other.coins;assert(g.discardToken(other));assert.equal(other.coins,coins);assert.equal(other.chips.length,6);}assert.deepEqual(g.TOKEN_ART_WEIGHTS.map(x=>x.weight),[55,25,20]);});
test('All eight rules are reachable in normal runs, never repeat within a floor, and survive save/load',()=>{const seen=new Set();for(let seed=1;seed<=100;seed++)for(let n=1;n<=4;n++){const s=g.createState(rng(seed));s.floor=n;s.map=g.createFloorMap(n,rng(seed*9));const entry=s.map[0][0];Object.assign(s,{currentRoom:entry.id,visited:[entry.id],target:entry.target,spinsLeft:entry.spins});assert(!entry.rule);assert(!s.map.at(-1)[0].rule);const ids=s.map.flat().map(r=>r.rule).filter(Boolean);assert.equal(new Set(ids).size,ids.length);ids.forEach(id=>{assert(g.Depth.rules[id]);seen.add(id)});assert.deepEqual(g.decodeRun(g.encodeRun(s)).state.map,s.map);}assert.deepEqual([...seen].sort(),Object.keys(g.Depth.rules).sort());assert(seen.has('parity'));});
test('Interaction recipes reject incompatible colour and stray-tag pairings and expose real sources',()=>{const s=g.createState(()=>0);const set=names=>s.chips=names.map((n,id)=>g.createChip(g.CHIP_CATALOG.find(c=>c.name===n),id));set(['Velvet','Switchback']);assert(!g.activeSynergies(s).some(x=>x.id==='depth-color-thread'));set(['Velvet','Crimson']);let x=g.activeSynergies(s).find(x=>x.id==='depth-color-thread');assert.equal(x.bonusType,'interaction');assert.deepEqual(x.sources,['Velvet','Crimson']);s.relics=[{id:0,name:'Blood Pact'}];s.wheel[2].color='red';x=g.activeSynergies(s).find(x=>x.id==='red');assert.equal(x.bonusType,'bonus');assert(x.sources.includes('Blood Pact'));set(['Streak','Prime Lens']);s.wheel[1].mark='Hot';assert(!g.activeSynergies(s).some(x=>x.id==='depth-heat-engine'));});
test('Wheel comparison shows exact fractions and build effects without mutating the source',()=>{const s=g.createState(()=>0);s.items=[{id:0,name:'Duplicate'}];s.wheel[7].mark='Hot';const raw=JSON.stringify(s),p=g.previewWheelItem(s,0,7),rows=g.wheelComparison(s,p.wheel,7);assert.match(rows[0].before,/1 \/ 19/);assert.match(rows[0].after,/2 \/ 20/);assert.equal(JSON.stringify(s),raw);assert.equal(p.wheel[8].mark,'Hot');assert.equal(g.wheelSummary(p.wheel).marks.Hot,2);});
test('Context preview has exact target/spins, live status, duplicate pocket ranges, curse and all placed bets',()=>{const s=g.createState(()=>0);s.chips=[g.createChip(g.CHIP_CATALOG.find(c=>c.name==='Velvet'),0)];s.depth.room={...s.depth.room,color:'red',chain:2,lastMiss:true};s.chips[0].mutations=['Patient','Echo'];s.wheel.push({number:1,color:'red',mark:'Boosted'});const raw=JSON.stringify(s),p=g.previewBet(s,0,'outside','red');assert.equal(p.hits,10);assert.equal(p.total,20);assert.equal(p.remaining,20);assert(p.states.some(x=>x.includes('Patient bereit')));assert(p.max>p.min);assert.equal(JSON.stringify(s),raw);});
test('Bonusspin offers once per floor and pays exactly one bounded delta through reload',()=>{for(const r of [0,.07]){const s=victory(),p=g.pressOffer(s);assert(p);assert.equal(p.hits,9);assert.equal(p.total,19);assert(g.decodeRun(g.encodeRun(s)).ok);const before={score:s.score,coins:s.coins,chips:JSON.stringify(s.chips),total:s.totalScore};assert(g.settlePress(s,'spin',()=>r).ok);assert.equal(s.coins-before.coins,r===0?-2:4);assert.equal(s.score,before.score);assert.equal(s.totalScore,before.total);assert.equal(JSON.stringify(s.chips),before.chips);assert(g.decodeRun(g.encodeRun(s)).ok);const raw=JSON.stringify(s);assert(!g.settlePress(s,'spin').ok);assert.equal(JSON.stringify(s),raw);assert(g.nextRound(s));assert.equal(s.press,null);}const s=victory(),money=s.coins;assert(g.settlePress(s,'cash').ok);assert.equal(s.coins,money);});
test('Bonus is absent on intro, boss ; old saves default cleanly',()=>{const s=g.createState(()=>0);g.placeBet(s,0,'outside','red');g.startSpin(s);g.resolveSpin(s,s.wheel[1]);assert(!g.pressOffer(s));const raw=JSON.parse(g.encodeRun(s));delete raw.state.press;delete raw.state.pressFloor;delete raw.state.challengeTokens;delete raw.state.discoveries;assert(g.decodeRun(JSON.stringify(raw)).ok);const invalid=victory();invalid.press.bonus=999;assert(!g.decodeRun(g.encodeRun(invalid)).ok);});
test('New event trades are atomic; fusion identifies the removed mark; widening has a real cost',()=>{let s=event('stoker');s.wheel[1].mark='Boosted';s.tokens=Array.from({length:3},(_,id)=>({id,name:'Chip Token'}));const raw=JSON.stringify(s);assert(!g.resolveBuildEvent(s,'strip',{fieldIndex:1}).ok);assert.equal(JSON.stringify(s),raw);s.tokens=[];assert(g.resolveBuildEvent(s,'strip',{fieldIndex:1}).ok);assert.equal(s.tokens[0].name,'Rad Token');s=event('overprint');s.wheel[1].mark='Hot';s.wheel[2].mark='Gilded';const result=g.resolveBuildEvent(s,'fuse',{fieldIndex:1});assert(result.ok);assert.match(result.message,/Feld 3 verliert Gilded/);assert.equal(s.wheel[1].mark,'Boosted');assert(!s.wheel[2].mark);s=event('empty-seat');assert(g.resolveBuildEvent(s,'widen',{fieldIndex:1}).ok);assert.equal(s.nextTableSpinDebt,1);assert.equal(s.coins,35);assert(g.decodeRun(g.encodeRun(s)).ok);});
test('Cursed explicitly remains powerful at zero coins without debt or duplicate payout',()=>{const s=g.createState(()=>0);s.wheel[1].mark='Cursed';g.placeBet(s,0,'outside','red');g.startSpin(s);g.resolveSpin(s,s.wheel[1]);assert.equal(s.spinScore,40);assert(s.coins>=0);assert.match(g.Depth.pockets.Cursed.description,/auch bei 0 Münzen/);const coins=s.coins;assert(!g.resolveSpin(s,s.wheel[1]));assert.equal(s.coins,coins);});
test('Boss preparations give accurate zero odds and targeted stock without neutralizing the boss',()=>{const s=g.createState(()=>0);assert.match(g.bossPreparation(s),/1\/19.*3\/21/);for(let f=1;f<=4;f++){const s=floor(f),room=s.map.at(-2)[0];Object.assign(s,{phase:'shop',currentRoom:room.id,mapStep:s.map.length-2,visited:[room.id],coins:100});assert(g.rerollShop(s,()=>0));assert.equal(s.shopOffers.length,4);assert.equal(s.shopOffers[2].type,'token');assert.equal(s.shopOffers[3].type,'item');assert(g.bossPreparation(s).length>50);}});

test('Copied Hot pockets share successful number heat, reset on room entry, and keep physical table heat separate',()=>{const s=g.createState(()=>0);s.target=1e9;s.wheel[1].mark='Hot';s.wheel.push({...s.wheel[1]});s.relics=[{id:0,name:'Kiln'}];g.placeBet(s,0,'number',1);g.startSpin(s);g.resolveSpin(s,s.wheel[1],()=>.99,1);assert.equal(s.spinScore,100);g.startSpin(s);g.resolveSpin(s,s.wheel[19],()=>.99,19);assert.equal(s.spinScore,156.25);assert.equal(s.depth.room.heat[1],1);assert.equal(s.depth.room.heat[19],1);g.Depth.resetRoom(s);assert.equal(g.Depth.context(s,s.wheel[19],19).hotHeat,0);});
