const assert = require("node:assert/strict");
const game = require("./full-roster.fixture.js");
const {createState,checkWin,calculateBetScore,startSpin,resolveSpin,nextRound,placeBet,returnChip,HIGH_ROLLER}=game;
let checks=0; function test(name,fn){fn();checks++;console.log("PASS "+name)}
test("All outside bets reject zero",()=>{for(const value of ["red","black","odd","even","low","high"])assert.equal(checkWin({type:"outside",value},{number:0,color:"green"}),false)});
test("All 19 number results and outside boundaries",()=>{for(let n=0;n<19;n++){let r={number:n,color:n===0?"green":n%2?"red":"black"};for(let v=0;v<19;v++)assert.equal(checkWin({type:"number",value:v},r),v===n);for(const [value,win] of [["low",n>=1&&n<=9],["high",n>=10],["odd",n%2===1],["even",n>0&&n%2===0]])assert.equal(checkWin({type:"outside",value},r),win)}});
test("Bonuses apply only to matching bet types",()=>{const s=createState();for(const chip of s.chips.slice(0,5)){for(const value of ["red","black","odd","even","low","high"]){const match=chip.bonus===value||(chip.bonus==="parity"&&["odd","even"].includes(value));assert.equal(calculateBetScore({chip,type:"outside",value}),match?30:20)}assert.equal(calculateBetScore({chip,type:"number",value:3}),chip.name==="Sniper"?300:100)}assert.equal(calculateBetScore({chip:HIGH_ROLLER,type:"outside",value:"high"}),30)});
test("No bets and duplicate spins cannot consume a spin",()=>{const s=createState();assert.equal(startSpin(s),false);assert.equal(s.spinsLeft,5);placeBet(s,0,"number",1);assert(startSpin(s));assert.equal(startSpin(s),false);assert.equal(s.spinsLeft,4);assert.equal(placeBet(s,1,"outside","red"),false);assert.equal(returnChip(s,0),false)});
test("Several chips can share a bet and return safely",()=>{const s=createState();for(let i=0;i<6;i++)placeBet(s,i,"outside","red");assert.equal(s.placedBets.length,6);for(let i=0;i<6;i++){returnChip(s,i);assert.equal(s.selectedChip,null)}assert.equal(s.placedBets.length,0)});
test("Winning round returns bets and blocks another spin",()=>{const s=createState();placeBet(s,0,"number",1);startSpin(s);resolveSpin(s,{number:1,color:"red"});assert.equal(s.phase,"won");assert.equal(s.score,100);assert.equal(s.placedBets.length,0);assert.equal(startSpin(s),false);assert((game.skipReward(s), nextRound(s)));assert.equal(s.phase,"map");assert(game.enterRoom(s,"table-2"));assert.equal(s.round,2);assert.equal(s.target,40);assert.equal(s.score,0);assert.equal(s.spinsLeft,6)});
test("Losing fifth spin cannot advance",()=>{const s=createState();placeBet(s,0,"number",1);for(let i=0;i<5;i++){assert(startSpin(s));resolveSpin(s,{number:2,color:"black"})}assert.equal(s.phase,"lost");assert.equal(s.placedBets.length,0);assert.equal((game.skipReward(s), nextRound(s)),false);assert.equal(startSpin(s),false)});
test("Reaching target on last spin wins",()=>{const s=createState();s.spinsLeft=1;placeBet(s,0,"number",1);startSpin(s);resolveSpin(s,{number:1,color:"red"});assert.equal(s.phase,"won")});
test("Zero multiplier applies after all chip scoring",()=>{const s=createState();placeBet(s,0,"number",0);placeBet(s,3,"number",0);startSpin(s);resolveSpin(s,{number:0,color:"green"});assert.equal(s.spinScore,300)});
test("Streak persists between tables and resets on a loss",()=>{const s=createState();placeBet(s,5,"number",1);startSpin(s);resolveSpin(s,{number:1,color:"red"});assert.equal(s.spinScore,125);assert.equal(s.chips[5].streak,1);(game.skipReward(s), nextRound(s));assert(game.enterRoom(s,"table-2"));assert.equal(s.chips[5].streak,1);placeBet(s,5,"number",1);startSpin(s);resolveSpin(s,{number:2,color:"black"});assert.equal(s.chips[5].streak,0)});
test("No duplicate chip bets and invalid fields rejected",()=>{const s=createState();placeBet(s,0,"number",1);placeBet(s,0,"number",2);assert.equal(s.placedBets.length,1);assert.equal(s.placedBets[0].value,2);assert.equal(placeBet(s,0,"number",99),false)});
console.log(checks+" logic tests passed");
