const {test}=require('node:test'),assert=require('node:assert/strict'),g=require('../script.js'),D=g.Depth;
const state=()=>g.createState(()=>0,g.ACHIEVEMENTS.map(a=>a.id));
function fire(s,index,random=()=>.999999){assert(g.startSpin(s));assert(g.resolveSpin(s,s.wheel[index],random,index));return s.spinScore;}
function build(names,relics=[],mark){const s=state();s.chips=names.map((n,id)=>g.createChip(g.CHIP_CATALOG.find(c=>c.name===n),id));s.nextChipId=names.length;s.relics=relics.map((name,id)=>({name,id}));s.nextRelicId=relics.length;if(mark)s.wheel[1].mark=mark;return s;}
function again(s){s.phase='ready';s.target=1e9;s.spinsLeft=8;}
test('Marked duplicate numbers resolve the landed pocket only; preview includes both',()=>{const s=state();s.wheel.push({number:1,color:'red',mark:'Gilded'});g.placeBet(s,0,'number',1);assert.equal(g.previewBet(s,0,'number',1).hits,2);const a=structuredClone(s),b=structuredClone(s);fire(a,1);fire(b,19);assert.equal(b.coins-a.coins,2);assert.equal(a.depth.trace.length,0);assert(b.depth.trace.some(e=>e.label==='+2 Münzen'));});
test('Pocket scoring stages precede ordered relics, with exactly one bounded retrigger',()=>{const s=build(['Basic'],['Blood Pact','Lucky Seven'],'Boosted');s.wheel[1].number=7;g.placeBet(s,0,'number',7);assert.equal(fire(s,1),325);assert.equal(s.depth.trace[0].after,150);assert(s.depth.trace.every(e=>e.depth===0));});
test('Every tool preserves metadata through clone/rewrite and consumes once; failed changes atomic',()=>{for(const name of Object.keys(D.tools)){const s=state();s.items=[{id:0,name}];assert(g.useWheelItem(s,0,1).ok);assert.equal(s.wheel[1].mark,D.tools[name].mark);assert.equal(s.depth.run.mods,1);assert(!g.useWheelItem(s,0,1).ok);assert(g.decodeRun(g.encodeRun(s)).ok);}const s=state();s.wheel[1].mark='Hot';for(const name of ['Duplicate','Rewrite','Clone']){s.items=[{id:0,name}];assert(g.useWheelItem(s,0,1,{number:7,targetIndex:2}).ok);assert(s.wheel.some(f=>f.mark==='Hot'));}s.items=[{id:0,name:'Heat'}];const before=JSON.stringify(s);assert(!g.useWheelItem(s,0,1).ok);assert.equal(JSON.stringify(s),before);});
test('Heat grows only after a winning spin and resets per room; mutations mint/temper without recursion',()=>{const s=build(['Basic'],[],'Hot');again(s);g.placeBet(s,0,'outside','red');assert.equal(fire(s,1),20);assert.equal(fire(s,1),25);assert.equal(s.depth.room.heat[1],2);D.resetRoom(s);assert.equal(s.depth.room.heat[1],undefined);const t=build(['Basic']);again(t);t.chips[0].mutations=['Tempered'];g.placeBet(t,0,'number',1);assert.equal(fire(t,1),100);assert.equal(t.wheel[1].mark,'Hot');assert.equal(fire(t,1),125);t.chips[0].mutations=['Minted'];t.wheel[1].mark='Gilded';const coins=t.coins;fire(t,1);assert.equal(t.coins-coins,3);});
test('New events are transactional, have a free exit, and do not repeat grants',()=>{for(const event of D.events){const s=state(),room=s.map.flat().find(r=>r.type==='event');Object.assign(s,{phase:'event',currentRoom:room.id,mapStep:s.map.findIndex(row=>row.includes(room)),visited:[room.id],eventId:event.id,coins:30});s.chips[0].mutations=['Polished'];s.wheel[1].mark='Hot';const before=JSON.stringify(s);assert(!g.resolveBuildEvent(s,event.choices[0].id,{}).ok);assert.equal(JSON.stringify(s),before);const choice=event.choices[0];if(event.mark==='Hot')s.wheel[1].mark='Boosted';assert(g.resolveBuildEvent(s,choice.id,{fieldIndex:1,chipId:0,mutation:'Polished'}).ok,event.id);assert(!g.resolveBuildEvent(s,choice.id,{fieldIndex:1,chipId:0}).ok);assert(g.decodeRun(g.encodeRun(s)).ok,event.id);const exit=state();Object.assign(exit,{phase:'event',currentRoom:room.id,mapStep:s.map.findIndex(row=>row.includes(room)),visited:[room.id],eventId:event.id});assert(g.resolveBuildEvent(exit,'leave').ok);}});
test('All eight room rules alter a choice and survive save round-trips; first room remains plain',()=>{assert(!state().map[0][0].rule);for(const key of Object.keys(D.rules)){const s=state();s.map[0][0].rule=key;g.placeBet(s,0,'outside','red');assert.equal(g.decodeRun(g.encodeRun(s)).state.map[0][0].rule,key);fire(s,1);assert(Number.isFinite(s.spinScore));}const a=state(),b=state();a.map[0][0].rule=b.map[0][0].rule='precision';g.placeBet(a,0,'number',1);g.placeBet(b,0,'outside','red');assert.equal(fire(a,1),200);assert.equal(fire(b,1),13);});
test('Old saves migrate without new rules and malformed modifier data is rejected',()=>{const s=state(),raw=JSON.parse(g.encodeRun(s));delete raw.state.depth;assert(g.decodeRun(JSON.stringify(raw)).ok);assert.deepEqual(g.decodeRun(JSON.stringify(raw)).state.depth,D.fresh());for(const mutate of [x=>x.state.wheel[0].mark='bogus',x=>x.state.depth.room.heat[1]=Infinity,x=>x.state.map[0][0].rule='bogus']){const x=JSON.parse(g.encodeRun(s));mutate(x);assert(!g.decodeRun(JSON.stringify(x)).ok);}});
test('Double Zero temporary pockets never become permanent through Tempered or saves',()=>{const s=state(),boss=s.map.at(-1)[0],prev=s.map.at(-2)[0];Object.assign(s,{phase:'map',currentRoom:prev.id,mapStep:s.map.length-2,visited:[prev.id]});assert(g.enterRoom(s,boss.id));s.chips[0].mutations=['Tempered'];g.placeBet(s,0,'number',0);fire(s,s.wheel.length-1);assert(!s.wheel.at(-1).mark);assert(g.decodeRun(g.encodeRun(s)).ok);});
test('Challenge unlocks merge, contain no permanent stats and gate reward pools',()=>{const s=build(['Zero Coil']);again(s);g.placeBet(s,0,'number',0);for(let i=0;i<3;i++)fire(s,0);assert(s.depth.earned.includes('depth-zero'));let profile=g.recordAchievementSpin(null,s.lastSpin,false);assert(profile.unlocks.includes('depth-zero'));profile=g.mergeProgress(profile,{version:1,depthUnlocks:['depth-mods']});assert(profile.unlocks.includes('depth-mods'));assert(g.contentUnlocked(g.createState(()=>0,profile.unlocks),D.chips.find(c=>c.name==='Zero Coil')));assert.equal(g.createState(()=>0,profile.unlocks).chips[0].name,'Basic');});
test('Six different setup builds grow strong with distinct conditions and bounded traces',()=>{
 const cases=[['red',['Velvet','Crimson'],['Blood Pact'],null,'outside','red',1],['precision',['Prime Lens','Engraver'],['Bullseye','Closed Circuit'],'Boosted','number',7,7],['zero',['Zero','Zero Coil'],['Green Seal','Zero Bell'],null,'number',0,0],['gold',['Dividend','Prospector'],['Reserve Note','Lacquer'],'Gilded','outside','red',1],['chaos',['Wildfire','Engraver'],['Prism Seal'],'Boosted','number',1,1],['wheel',['Engraver','Cinder'],['Lacquer','Kiln'],'Hot','number',1,1]];
 for(const [name,names,relics,mark,type,value,index]of cases){const s=build(names,relics);again(s);s.coins=30;if(mark)s.wheel[index].mark=mark;if(name==='precision'){s.wheel=s.wheel.map((f,i)=>({number:i%8,color:i%8===0?'green':i%2?'red':'black',mark:'Boosted'}));}if(name==='chaos'){s.wheel[2].mark='Gilded';s.wheel[3].mark='Hot';}for(const c of s.chips)g.placeBet(s,c.id,type,value);const preview=g.previewBet(s,0,type,value);let peak=0;for(let i=0;i<3;i++)peak=Math.max(peak,fire(s,index,()=>0));assert(peak>=100,name+' '+peak);assert(s.depth.trace.length<=32);assert(preview.max>=preview.min);console.log('BUILD',name,'peak',peak);}
});

test('Heat follows physical pockets through deletion/duplication; a copy starts cold',()=>{const s=state();s.depth.room.heat={1:2,3:4};s.items=[{id:0,name:'Duplicate'}];assert(g.useWheelItem(s,0,1).ok);assert.deepEqual(s.depth.room.heat,{1:2,4:4});s.items=[{id:1,name:'Delete'}];assert(g.useWheelItem(s,1,0).ok);assert.deepEqual(s.depth.room.heat,{0:2,3:4});s.items=[{id:2,name:'Gild'}];assert(g.useWheelItem(s,2,3).ok);assert.equal(s.depth.room.heat[3],4);});
