const {webkit,chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),g=require('../script.js');
const out=path.resolve(__dirname,'../test-results/feel');fs.mkdirSync(out,{recursive:true});
(async()=>{
 for(const engine of (process.env.ENGINE==='webkit'?[webkit]:process.env.ENGINE==='chromium'?[chromium]:[webkit,chromium])){
  const browser=await engine.launch(engine===chromium?{channel:'msedge'}:{});
  try{for(const [name,width,height,touch,reduced]of [['ipad-short',1180,680,true,false],['ipad-min',1180,600,true,true],['phone',390,844,true,true],['desktop',1366,768,false,false]]){
   if(process.env.PROFILE&&!name.includes(process.env.PROFILE))continue;const p=await browser.newPage({viewport:{width,height},hasTouch:touch,isMobile:touch,reducedMotion:reduced?'reduce':'no-preference'}),errors=[];
   p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>Math.random=()=>.065);await p.goto('file:///C:/Users/repin/Desktop/chat/index.html');await p.locator('#start-run').click();
   async function seed(s){const save=g.encodeRun(s);assert(g.decodeRun(save).ok);await p.evaluate(v=>{localStorage.clear();localStorage.setItem('roguelette-run-v1',v);},save);await p.reload();await p.locator('#resume-run').click();}
   async function fit(id){assert(await p.locator(id).evaluate(e=>{const r=e.getBoundingClientRect();return r.x>=-1&&r.right<=innerWidth+1&&r.y>=-1&&r.bottom<=innerHeight+1&&e.scrollWidth<=e.clientWidth+1;}),name+' '+id+' fits');}
   async function inspect(){await p.locator('#chips [data-chip="0"]').click();if(touch){await fit('#chip-peek');assert.equal(await p.locator('.bet-stack .chip-element').count(),0);await p.screenshot({path:path.join(out,engine.name()+'-'+name+'-peek.png')});await p.locator('#peek-action').click();}}
   await inspect();await p.locator('#outside-bets .bet-target').first().click();assert.equal(await p.locator('.bet-stack .chip-element').count(),1);
   if(touch){await p.locator('.bet-stack .chip-element').click();assert.equal(await p.locator('.bet-stack .chip-element').count(),1,'inspection must not return chip');await p.locator('#peek-action').click();assert.equal(await p.locator('.bet-stack .chip-element').count(),0);await inspect();await p.locator('#outside-bets .bet-target').first().click();}
   await p.locator('#spin').click();await p.locator('#room-receipt').waitFor({state:'visible'});await fit('#room-receipt');assert.equal(await p.locator('#score').innerText(),'20');await p.screenshot({path:path.join(out,engine.name()+'-'+name+'-receipt.png')});await p.locator('#receipt-continue').click();assert(await p.locator('#map-dialog').isVisible());await fit('#map-dialog');await p.screenshot({path:path.join(out,engine.name()+'-'+name+'-map.png')});
   const shop=g.createState(()=>0);Object.assign(shop,{phase:'map',mapStep:1,currentRoom:'table-2',visited:['entry','table-2'],coins:30});g.enterRoom(shop,'shop',()=>0);await seed(shop);await p.locator('#buy-slot-upgrade').click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('roguelette-run-v1')).state.capacity),7);await fit('#room-dialog');await p.screenshot({path:path.join(out,engine.name()+'-'+name+'-shop.png')});await p.locator('#purchase-offer').click();await p.locator('#claim-token').waitFor({state:'visible'});await p.locator('#claim-token').click();assert(await p.locator('.goods-card.sold').count());
   const workshop=g.createState(()=>0),room=workshop.map.flat().find(r=>r.type==='workshop');Object.assign(workshop,{phase:'workshop',mapStep:workshop.map.findIndex(row=>row.includes(room)),currentRoom:room.id,visited:[room.id],coins:20});await seed(workshop);await p.locator('#open-chip-workbench').click();await p.locator('[data-work-chip="0"]').click();await fit('#chip-workbench');await p.screenshot({path:path.join(out,engine.name()+'-'+name+'-bench.png')});await p.locator('#apply-chip-work').click();assert(await p.locator('#apply-chip-work').isDisabled());assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('roguelette-run-v1')).state.chips[0].mutations),['Polished']);await p.reload();await p.locator('#resume-run').click();await p.locator('#open-chip-workbench').click();await p.locator('[data-work-chip="0"]').click();assert(await p.locator('#apply-chip-work').isDisabled());
   const rich=g.createState(()=>0);rich.floor=4;rich.map=g.createFloorMap(4,()=>0);const boss=rich.map.at(-1)[0];Object.assign(rich,{currentRoom:boss.id,mapStep:rich.map.length-1,visited:[boss.id],target:boss.target,spinsLeft:boss.spins});rich.chips=[g.createChip(g.CHIP_TYPES[1],0),g.createChip(g.CHIP_TYPES[1],1)];rich.nextChipId=2;rich.chips.forEach(c=>c.mutations=['Polished','Echo']);rich.relics=[{id:0,name:'Blood Pact'},{id:1,name:'Lucky Seven'}];rich.nextRelicId=2;rich.wheel[2].color='red';g.placeBet(rich,0,'outside','red');g.placeBet(rich,1,'outside','red');await seed(rich);
   await p.locator('#show-synergies').click();await fit('#synergy-dialog');assert.match(await p.locator('#synergy-dialog').innerText(),/Roter Faden|Resonanz/);await p.locator('#synergy-dialog button').click();
   if(!reduced){await p.evaluate(()=>{window.scoreSamples=[];new MutationObserver(()=>window.scoreSamples.push(document.querySelector('#score').textContent)).observe(document.querySelector('#score'),{childList:true});});}
   await p.locator('#spin').click();await p.waitForFunction(()=>!document.querySelector('#spin').disabled);if(!reduced)assert((await p.evaluate(()=>new Set(window.scoreSamples).size))>3,'score rattles through integers: '+JSON.stringify(await p.evaluate(()=>window.scoreSamples)));
   if(width>=1100)assert(await p.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1),'no page overflow');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:path.join(out,engine.name()+'-'+name+'-table.png')});assert.deepEqual(errors,[]);await p.close();console.log('PASS '+engine.name()+' '+name);
  }}finally{await browser.close();}
 }
})().catch(e=>{console.error(e);process.exitCode=1;});
