const {test}=require('node:test'),assert=require('node:assert/strict'),g=require('../script.js');
function win(s){for(const c of s.chips.slice(0,3))g.placeBet(s,c.id,'number',1);while(s.phase==='ready'){assert(g.startSpin(s));g.resolveSpin(s,{number:1,color:'red'},()=>1);}assert.equal(s.phase,'won');assert(g.nextRound(s));}
test('Generated paths have valid edges, no dead ends, and cannot jump lanes',()=>{const variants=new Set();for(let seed=0;seed<40;seed++){let n=seed+1;const rng=()=>((n=(n*1664525+1013904223)>>>0)/4294967296);const s=g.createState(rng);variants.add(JSON.stringify(s.map));for(let row=0;row<s.map.length-1;row++)for(const room of s.map[row]){assert(room.next.length>0);assert(room.next.every(id=>s.map[row+1].some(n=>n.id===id)));if(s.map[row].length>1&&s.map[row+1].length>1)assert(room.next.length<3);}s.phase='map';s.mapStep=1;s.currentRoom='table-2';const blocked=s.map[2].find(n=>!g.currentRoom(s).next.includes(n.id));assert(blocked);const before=JSON.stringify(s);assert(!g.enterRoom(s,blocked.id));assert.equal(JSON.stringify(s),before);}assert(variants.size>5);});
test('Four full floors preserve builds, scores, money and permanent wheel edits',()=>{const s=g.createState(()=>0);s.chips.push(g.createChip(g.CHIP_TYPES[1],s.nextChipId++));s.chips[1].mutations=['Lucky'];g.updateBuildStats(s);s.items=[{id:0,name:'Repaint'}];s.relics=[{id:0,name:'Blood Pact'}];s.wheel.push({number:1,color:'red'});for(let floor=1;floor<=4;floor++){win(s);const prefix=floor===1?'':'f'+floor+'-';for(const id of (floor===4?['stakes','final-shop','boss']:['table-2','shop','table-3','final-shop','boss'])){assert(g.enterRoom(s,prefix+id,()=>0));if(s.phase==='shop')assert(g.resolveRoom(s,'leave').ok);else win(s);}assert.equal(s.wheel.length,20);assert.equal(s.phase,floor===4?'complete':'floor-clear');if(floor<4){const before=JSON.stringify([s.chips,s.items,s.relics,s.wheel,s.coins,s.totalScore]);assert(g.advanceFloor(s,()=>0));assert.equal(s.floor,floor+1);assert.equal(JSON.stringify([s.chips,s.items,s.relics,s.wheel,s.coins,s.totalScore]),before);assert(!g.advanceFloor(s));}}assert.equal(s.cleared.length,22);assert.deepEqual(s.completedFloors,[1,2,3,4]);assert(!g.advanceFloor(s));});
function boss(floor){const s=g.createState(()=>0);s.floor=floor;s.map=g.createFloorMap(floor,()=>0);s.currentRoom='f'+floor+'-final-shop';s.mapStep=4;s.phase='map';assert(g.enterRoom(s,'f'+floor+'-boss'));return s;}
test('Taxman charges only losers, caps penalty and cannot create negative scores',()=>{const s=boss(2);s.chips=Array.from({length:6},(_,id)=>g.createChip(g.CHIP_TYPES[0],id));g.placeBet(s,0,'outside','red');for(let i=1;i<6;i++)g.placeBet(s,i,'outside','black');g.startSpin(s);g.resolveSpin(s,{number:1,color:'red'});assert.equal(s.lastSpin.bossPenalty,5);assert.equal(s.spinScore,15);s.placedBets=[];g.placeBet(s,0,'outside','black');g.startSpin(s);g.resolveSpin(s,{number:1,color:'red'});assert.equal(s.spinScore,0);assert.equal(s.wheel.length,19);});
test('Minimalist allows three chips, moving bets and returning chips',()=>{const s=boss(3);s.chips=Array.from({length:4},(_,id)=>g.createChip(g.CHIP_TYPES[0],id));for(let i=0;i<3;i++)assert(g.placeBet(s,i,'number',1));assert(!g.placeBet(s,3,'number',1));assert(g.placeBet(s,0,'outside','red'));assert(g.returnChip(s,1));assert(g.placeBet(s,3,'number',1));assert.equal(s.placedBets.length,3);s.currentRoom='f3-entry';assert(g.placeBet(s,1,'number',1));});

test('Penthouse has a mandatory final shop, discounts survive refill, premium workshop grants once',()=>{const s=g.createState();s.floor=4;s.map=g.createFloorMap(4,()=>0);s.currentRoom='f4-workshop';s.phase='workshop';s.mapStep=1;s.coins=50;assert(g.resolveRoom(s,'Mitosis').ok);assert.equal(s.items[0].name,'Mitosis');assert(!g.resolveRoom(s,'Clone').ok);assert(!g.enterRoom(s,'f4-boss'));assert(g.enterRoom(s,'f4-final-shop',()=>0));assert.deepEqual(s.shopOffers.slice(0,3).map(o=>o.price),[4,6,8]);assert(g.rerollShop(s,()=>0));assert.equal(s.shopOffers[0].price,4);g.resolveRoom(s,'leave');assert(g.enterRoom(s,'f4-boss'));assert.equal(s.spinsLeft,8);g.placeBet(s,0,'number',0);g.startSpin(s);g.resolveSpin(s,{number:0,color:'green'});assert.equal(s.lastSpin.housePenalty,20);assert.equal(s.spinScore,60);assert.equal(s.wheel.length,19);});
