const {webkit,chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),http=require('node:http'),path=require('node:path'),g=require('../script.js');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results/ipad');fs.mkdirSync(out,{recursive:true});
const profiles=[['ipad10-portrait',820,1180],['ipad10-landscape',1180,820],['pro11-portrait',834,1194],['pro11-landscape',1194,834],['pro11-modern-portrait',834,1210],['pro11-modern-landscape',1210,834],['pro12-portrait',1024,1366],['pro12-landscape',1366,1024],['pro13-portrait',1032,1376],['pro13-landscape',1376,1032],['ipad10-safari-bars',1180,720],['ipad10-portrait-bars',820,1080],['split-view',744,1024],['split-narrow',507,1024],['stage-manager',900,700]];
(async()=>{const server=http.createServer((req,res)=>{const filename=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(!filename.startsWith(root+path.sep)||!fs.existsSync(filename)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',filename.endsWith('.css')?'text/css':filename.endsWith('.js')?'text/javascript':'text/html');res.end(fs.readFileSync(filename));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/index.html',errors=[],measurements=[];
try{for(const engine of (process.env.TABLET_ENGINE?[process.env.TABLET_ENGINE]:['webkit','chromium'])){const browser=await (engine==='webkit'?webkit:chromium).launch(engine==='webkit'?{headless:true}:{headless:true,channel:'msedge'});try{for(const [name,width,height]of profiles){if(process.env.TABLET_PROFILE&&!name.includes(process.env.TABLET_PROFILE))continue;const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,isMobile:true,hasTouch:true,reducedMotion:'reduce'}),p=await context.newPage();p.on('pageerror',e=>errors.push(name+': '+e.message));await p.addInitScript(()=>Math.random=()=>.065);await p.goto(url);await p.locator('#start-run').tap();await p.locator('#chips [data-chip="0"]').tap();await p.locator('#outside-bets .bet-target').first().tap();assert(await p.locator('#outside-bets .chip-element').count());const sizes=await p.locator('.bet-target, .top-actions button, #spin, #outside-bets .chip-element').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {id:e.id||e.className,w:r.width,h:r.height};}));assert(sizes.every(r=>r.w>=43&&r.h>=43),name+JSON.stringify(sizes.filter(r=>r.w<43||r.h<43)));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+' horizontal overflow');measurements.push({engine,name,width,height,pageHeight:await p.evaluate(()=>document.documentElement.scrollHeight)});await p.screenshot({path:path.join(out,engine+'-'+name+'-table.png'),fullPage:true});await p.locator('#spin').tap();await p.waitForFunction(()=>!document.querySelector('#spin').disabled);assert.equal(await p.locator('#score').innerText(),'20');await p.reload();await p.locator('#resume-run').tap();assert.equal(await p.locator('#score').innerText(),'20');
// Rotation preserves state and control access.
await p.setViewportSize({width:height,height:width});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.setViewportSize({width,height});
if(!['ipad10-portrait','ipad10-landscape','pro13-portrait','pro13-landscape','split-narrow','split-view','stage-manager'].includes(name)){await context.close();console.log('PASS '+engine+' '+name+' table/rotation');continue;}
async function seed(s){await p.evaluate(save=>localStorage.setItem('roguelette-run-v1',save),g.encodeRun(s,null,null));await p.reload();await p.locator('#resume-run').tap();}
async function scene(id,suffix){assert(await p.locator(id).evaluate(e=>e.scrollWidth<=e.clientWidth+1),name+' '+id+' overflow');await p.screenshot({path:path.join(out,engine+'-'+name+'-'+suffix+'.png')});}
const map=g.createState(()=>0);Object.assign(map,{phase:'map',mapStep:3,currentRoom:'unknown',visited:['entry','table-2','shop','unknown'],cleared:['entry','table-2','shop','unknown']});await seed(map);await p.locator('[data-room="detour-workshop"]').tap();assert.match(await p.locator('#map-room-detail').innerText(),/Delete oder Rewrite/);await scene('#map-dialog','map');await p.locator('#enter-map-room').tap();await p.getByRole('button',{name:/^Delete —/}).tap();await p.locator('#wheel-fields button').first().tap();await p.locator('#apply-item').tap();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('roguelette-run-v1')).state.wheel.length),18);
const shop=g.createState(()=>0);Object.assign(shop,{phase:'map',mapStep:1,currentRoom:'table-2',visited:['entry','table-2'],coins:14});g.enterRoom(shop,'shop',()=>0);await seed(shop);await p.locator('.goods-card').nth(1).tap();await scene('#room-dialog','shop');await p.locator('#purchase-offer').tap();await scene('#token-dialog','slot');await p.locator('#claim-token').tap();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('roguelette-run-v1')).state.coins),8);
const wheel=g.createState(()=>0);wheel.items=[{id:0,name:'Rewrite'}];wheel.nextItemId=1;wheel.wheel=[...wheel.wheel,...wheel.wheel];await seed(wheel);await p.locator('#items button').first().tap();const fields=await p.locator('#wheel-fields button').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {w:r.width,h:r.height,x:r.x,y:r.y};}));assert(fields.every(r=>r.w>=43&&r.h>=43),name+' workshop touch size');await p.locator('#wheel-fields button').first().tap();await scene('#workshop-dialog','workshop');await p.locator('#rewrite-number').fill('7');await p.locator('#apply-item').tap();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('roguelette-run-v1')).state.wheel[0].number),7);await context.close();console.log('PASS '+engine+' '+name);}}finally{await browser.close();}}assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'measurements.json'),JSON.stringify(measurements,null,2));console.log('PASS tablet touch targets, tap/place/spin/reload/rotation, map/workshop, purchase/slot, 38-field edit, no horizontal overflow or JS errors');}finally{await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exit(1)});
