const passDetour=require('./route.fixture.cjs');
const {test}=require('node:test');
const assert=require('node:assert/strict');
const g=require('../script.js');
function win(s){for(const c of s.chips)g.placeBet(s,c.id,'number',1);while(s.phase==='ready'){assert(g.startSpin(s));g.resolveSpin(s,{number:1,color:'red'});}assert.equal(s.phase,'won');g.skipReward(s);assert(g.nextRound(s));}
function boss(){const s=g.createState(()=>0);win(s);g.enterRoom(s,'stakes');win(s);g.enterRoom(s,'workshop');g.resolveRoom(s,'leave');g.enterRoom(s,'unknown',()=>0);g.resolveRoom(s,'safe');(passDetour(s),g.enterRoom(s,'final-shop'));g.resolveRoom(s,'leave');g.enterRoom(s,'boss');return s;}
test('Map advances only after rewards and only one row at a time',()=>{const s=g.createState(()=>0);assert(!g.enterRoom(s,'boss'));win(s);assert.equal(s.coins,6);assert(!g.enterRoom(s,'shop'));assert(g.enterRoom(s,'stakes'));assert.equal(s.spinsLeft,5);assert.equal(s.target,60);assert(!g.enterRoom(s,'table-2'));win(s);assert.equal(s.coins,14);assert(!g.enterRoom(s,'entry'));assert.equal(g.startSpin(s),false);});
test('Shop charges once, locks pending outcome, increasing refills reset in next shop',()=>{const s=g.createState(()=>0);win(s);g.enterRoom(s,'table-2');win(s);g.enterRoom(s,'shop',()=>0);assert.deepEqual(s.shopOffers.map(o=>o.type),['slot','slot','slot','item']);assert.equal(s.shopOffers[0].price,6);assert(g.buyOffer(s,0,null,()=>.2).ok);assert.equal(s.coins,4);assert.equal(s.phase,'slot');assert(!g.buyOffer(s,0).ok);assert(!g.rerollShop(s));assert(g.discardToken(s));const before=JSON.stringify(s);assert(!g.buyOffer(s,1).ok);assert.equal(JSON.stringify(s),before);assert(g.rerollShop(s,()=>0));assert.equal(s.coins,0);assert.equal(s.rerolls,1);assert.equal(g.refillPrice(s),7);assert(!g.rerollShop(s));g.resolveRoom(s,'leave');g.enterRoom(s,'unknown',()=>0);g.resolveRoom(s,'safe');(passDetour(s),g.enterRoom(s,'final-shop'));assert.equal(s.rerolls,0);});
test('Workshop and event are single use; risky loss never makes currency negative',()=>{const s=g.createState(()=>0);win(s);g.enterRoom(s,'stakes');win(s);g.enterRoom(s,'workshop');assert(g.resolveRoom(s,'Duplicate').ok);assert.equal(s.items.length,1);assert(!g.resolveRoom(s,'Duplicate').ok);g.enterRoom(s,'unknown',()=>0);s.coins=3;assert(g.resolveRoom(s,'risk',()=>.5).ok);assert.equal(s.coins,0);assert(!g.resolveRoom(s,'safe').ok);});
test('Boss temporary fields, item safety, cleanup and finite victory',()=>{const s=boss();assert.equal(s.wheel.length,21);s.items.push({id:s.nextItemId++,name:'Duplicate'});const before=JSON.stringify(s);assert(!g.useWheelItem(s,s.items[0].id,20).ok);assert.equal(JSON.stringify(s),before);assert(g.useWheelItem(s,s.items[0].id,1).ok);assert.equal(s.wheel.length,22);assert.equal(s.bossWheel.length,20);win(s);assert.equal(s.phase,'floor-clear');assert.equal(s.wheel.length,20);assert.equal(s.bossWheel,null);assert.equal(s.cleared.length,7);assert(s.totalScore>=s.bestSpin);assert(!g.nextRound(s));assert(!g.enterRoom(s,'entry'));});
test('Boss loss restores permanent wheel and reset clears the run',()=>{const s=boss();s.spinsLeft=1;g.placeBet(s,0,'number',1);g.startSpin(s);g.resolveSpin(s,{number:2,color:'black'});assert.equal(s.phase,'lost');assert.equal(s.wheel.length,19);assert.equal(s.bossWheel,null);const fresh=g.createState(()=>0);assert.equal(fresh.coins,0);assert.equal(fresh.bestSpin,0);assert.deepEqual(fresh.visited,['entry']);});
