const {webkit,chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs'),g=require('../script.js');
(async()=>{fs.mkdirSync('test-results/onboarding',{recursive:true});for(const engine of [webkit,chromium]){const b=await engine.launch(engine===chromium?{channel:'msedge'}:{});try{for(const [name,width,height,touch]of [['ipad',1180,600,true],['desktop',1366,768,false],['phone',390,844,true]]){
 if(process.env.PROFILE&&name!==process.env.PROFILE)continue;
 const p=await b.newPage({viewport:{width,height},hasTouch:touch,reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>Math.random=()=>.065);await p.goto('file:///C:/Users/repin/Desktop/chat/index.html');await p.locator('#start-run').click();const card=p.locator('#onboarding-card');await card.waitFor({state:'visible'});assert.match(await card.innerText(),/1 · WÄHLE/);
 const fit=async()=>{assert(await card.evaluate(e=>{const r=e.getBoundingClientRect();return r.x>=0&&r.y>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1;}));if(width>1100)assert(await p.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1));};await fit();await p.screenshot({path:'test-results/onboarding/'+engine.name()+'-'+name+'-intro.png'});
 await p.locator('#chips [data-chip="0"]').click();if(touch)await p.locator('#peek-action').click();assert.match(await card.innerText(),/2 · SETZE/);await p.getByRole('button',{name:'Auf ROT setzen',exact:true}).click();assert.match(await card.innerText(),/3 · SCHLAGE/);assert.match(await p.locator('#context-preview').innerText(),/Chance: 9 \/ 19 · Treffer: \+20/);await fit();await p.screenshot({path:'test-results/onboarding/'+engine.name()+'-'+name+'-bet.png'});
 await p.locator('#spin').click();await p.locator('#room-receipt').waitFor({state:'visible'});assert.equal(await p.locator('#score').innerText(),'20');assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('roguelette-onboarding-v1')).status),'completed');await p.locator('#receipt-continue').click();assert.equal(await card.getAttribute('data-mode'),'map');await p.locator('#onboarding-card button').click();await p.locator('#close-map').click();await p.locator('#show-map').click();assert(await card.isHidden());
 await p.reload();await p.locator('#resume-run').click();assert.notEqual(await card.getAttribute('data-mode'),'intro');
 const shop=g.createState(()=>0);Object.assign(shop,{phase:'map',mapStep:1,currentRoom:'table-2',visited:['entry','table-2'],coins:30});g.enterRoom(shop,'shop',()=>0);await p.evaluate(v=>localStorage.setItem('roguelette-run-v1',v),g.encodeRun(shop));await p.reload();await p.locator('#resume-run').click();assert.equal(await card.getAttribute('data-mode'),'shop');await fit();await p.screenshot({path:'test-results/onboarding/'+engine.name()+'-'+name+'-shop.png'});await p.locator('#onboarding-card button').click();await p.locator('.goods-card').nth(1).click();await p.locator('#purchase-offer').click();await p.locator('#claim-token').waitFor({state:'visible'});await p.locator('#claim-token').click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('roguelette-run-v1')).state.chips.length),2);
 await p.evaluate(()=>localStorage.clear());await p.reload();await p.locator('#start-run').click();await p.locator('#onboarding-card button').click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('roguelette-onboarding-v1')).status),'skipped');await p.reload();await p.locator('#resume-run').click();assert(await card.isHidden());await p.locator('#help').click();assert.equal(await p.locator('#help-dialog details[open]').count(),1);assert.equal(await p.locator('#help-dialog details').count(),8);assert.deepEqual(errors,[]);await p.close();console.log('PASS',engine.name(),name);
 }}finally{await b.close();}}})().catch(e=>{console.error(e);process.exitCode=1;});
