const {test}=require('node:test'),assert=require('node:assert/strict'),g=require('../script.js');
function rng(seed){let n=seed;return ()=>((n=(1664525*n+1013904223)>>>0)/2**32);}
function shop(floor=1){const s=g.createState(()=>0);s.floor=floor;s.map=g.createFloorMap(floor,()=>0);s.currentRoom=(floor===1?'':'f'+floor+'-')+'shop';if(floor===4)s.currentRoom='f4-final-shop';s.mapStep=s.map.findIndex(r=>r.some(n=>n.id===s.currentRoom));s.visited.push(s.currentRoom);s.phase='shop';s.coins=100;g.rerollShop(s,()=>0);s.rerolls=0;return s;}
function load(s){const r=g.decodeRun(g.encodeRun(s,null,null));assert(r.ok,JSON.stringify(r));return r.state;}
test('Economy: first normal route earns one slot, not the whole shop',()=>{const m=g.createFloorMap(1,()=>0);const income=m[0][0].payout+m[1].find(n=>n.id==='table-2').payout;assert.equal(income,10);const s=shop();assert.equal(s.shopOffers.slice(0,3).reduce((v,o)=>v+o.price,0),18);assert(income>=s.shopOffers[0].price&&income<2*s.shopOffers[0].price);assert.equal(m[1].find(n=>n.id==='stakes').payout,8);});
test('Endless income and prices stay bounded together; refill grows per visit',()=>{for(const floor of [1,2,4,5,10,50,100]){const s=shop(floor);assert(g.slotPrice(s)>=6&&g.slotPrice(s)<=16);assert(s.map.flat().filter(n=>n.payout).every(n=>n.payout<=20));const before=g.refillPrice(s);g.rerollShop(s,()=>0);assert.equal(g.refillPrice(s),before+3);}assert(g.slotPrice(shop(20))>g.slotPrice(shop(5)));});
test('All three slots share a mixed pool; buying rolls immediately and charges exactly once',()=>{for(const index of [0,1,2])for(const [roll,type]of [[.2,'chip'],[.6,'relic'],[.9,'item']]){const s=shop();const draws=[roll,.1,.1,.9];const before=s.coins;assert(g.buyOffer(s,index,null,()=>draws.shift()??.2).ok);assert.equal(s.phase,'slot');assert.equal(s.pendingToken.type,type);assert.equal(s.tokens.length,0);assert.equal(s.coins,before-6);const restored=load(s);assert.deepEqual(restored.pendingToken,s.pendingToken);assert(!g.buyOffer(restored,index).ok);assert(!g.rerollShop(restored));assert(g.claimToken(restored).ok);assert(!g.claimToken(restored).ok);assert.equal(restored.phase,'shop');assert(restored.shopOffers[index].sold);}});
test('Full inventory keeps a paid result until explicit replace or discard, no reroll',()=>{const s=shop();s.chips=Array.from({length:6},(_,id)=>g.createChip(g.CHIP_TYPES[0],id));s.nextChipId=6;assert(g.buyOffer(s,0,null,()=>.2).ok);assert(!g.claimToken(s).ok);const saved=load(s);assert.deepEqual(saved.pendingToken,s.pendingToken);assert(g.claimToken(saved,2).ok);assert.equal(saved.chips.length,6);assert.equal(saved.chips[2].id,6);const b=shop();g.buyOffer(b,0,null,()=>.2);const coins=b.coins;assert(g.discardToken(b));assert.equal(b.coins,coins);assert(b.shopOffers[0].sold);});
test('Map permutations preserve valid reachable tiers and multiple meaningful paths for 500 seeds',()=>{const variants=new Set();for(let seed=1;seed<=500;seed++){const floor=seed%8+1,s=g.createState(rng(seed));s.floor=floor;s.map=g.createFloorMap(floor,rng(seed));s.currentRoom=s.map[0][0].id;s.visited=[s.currentRoom];s.target=s.map[0][0].target;s.spinsLeft=s.map[0][0].spins;const m=s.map;assert(m.length-1>=4&&m.length-1<=6);assert(m.at(-1)[0].type==='boss');assert(m.at(-2).every(n=>n.type==='shop'));const counts=new Map([[m[0][0].id,1]]);for(let row=0;row<m.length-1;row++)for(const n of m[row]){assert(n.next.length);for(const id of n.next){assert(m[row+1].some(x=>x.id===id));counts.set(id,(counts.get(id)||0)+(counts.get(n.id)||0));}if(m[row].length>1&&m[row+1].length>1)assert(n.next.length<3);}assert([...counts.values()].every(v=>v>0));assert(counts.get(m.at(-1)[0].id)>=3);variants.add(JSON.stringify(m));if(floor>4){s.endless=true;s.normalWon=true;}assert.deepEqual(load(s).map,m);}assert(variants.size>400);});
test('Old saves retain old maps/payouts and old typed token inventory',()=>{const s=g.createState(()=>0);delete s.mapVersion;s.map=g.legacyFloorMap(1,()=>0);s.tokens=[{id:0,name:'Chip Token'},{id:1,name:'Relic Token'}];s.nextTokenId=2;const old=load(s);assert.equal(old.mapVersion,1);assert.equal(old.map[0][0].payout,10);assert(g.beginToken(old,0,()=>.2).ok);assert.equal(old.pendingToken.type,'chip');assert(g.claimToken(old).ok);});
test('Workshop preview is atomic and handles full wheel, Clone, Rewrite and boss fields',()=>{for(const name of Object.keys(g.WHEEL_ITEMS)){const s=g.createState(()=>0);s.items=[{id:0,name}];const before=JSON.stringify(s),preview=g.previewWheelItem(s,0,1,{number:7,targetIndex:2});assert(preview.ok,name);assert.equal(JSON.stringify(s),before);assert(g.useWheelItem(s,0,1,{number:7,targetIndex:2}).ok);assert.deepEqual(preview.wheel,s.wheel);}const s=g.createState(()=>0);s.items=[{id:0,name:'Duplicate'}];while(s.wheel.length<38)s.wheel.push({...s.wheel[1]});assert(!g.previewWheelItem(s,0,1).ok);});
test('Workshop room grants a tool and permits immediate editing without reopening combat',()=>{const s=g.createState(()=>0);s.mapStep=2;s.currentRoom='workshop';s.visited.push('workshop');s.phase='workshop';assert(g.resolveRoom(s,'Duplicate').ok);assert.equal(s.phase,'map');const preview=g.previewWheelItem(s,s.items[0].id,1);assert(preview.ok);assert(g.useWheelItem(s,s.items[0].id,1).ok);assert.equal(s.wheel.length,20);load(s);assert(!g.resolveRoom(s,'Duplicate').ok);});
test('Score formatting is consistently integral; content registry accepts future entries',()=>{for(const [value,text]of [[127.5000001,'128'],[127.49,'127'],[1500.5,'1.501'],[0,'0']])assert.equal(g.formatPoints(value),text);const chip={name:'Future test chip',symbol:'?',effect:'test'};g.CHIP_CATALOG.push(chip);try{const entry=g.buildTokenPool().find(c=>c.name===chip.name);assert.equal(entry.rarity,'Common');}finally{g.CHIP_CATALOG.pop();}});
