const {chromium}=require('playwright'),assert=require('node:assert/strict'),g=require('../script.js'),path=require('node:path'),fs=require('node:fs'),{pathToFileURL}=require('node:url');const url=pathToFileURL(path.join(__dirname,'../index.html')).href,out=path.join(__dirname,'../test-results/v12');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[];
const page=async s=>{const c=await browser.newContext({viewport:{width:1366,height:768},reducedMotion:'reduce'}),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(save=>{Math.random=()=>.065;if(save&&!sessionStorage.getItem('seeded')){localStorage.setItem('roguelette-run-v1',save);sessionStorage.setItem('seeded','1');}},s?g.encodeRun(s,null,null):null);await p.goto(url);return p;};
const shot=async(p,name)=>p.screenshot({path:path.join(out,name+'.png')});
const fit=async(p,id)=>assert(await p.locator(id).evaluate(d=>d.scrollWidth<=d.clientWidth+1),id+' overflows');
const saved=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('roguelette-run-v1')).state);
let p=await page();await shot(p,'menu');await p.locator('#start-run').click();for(const [w,h]of [[1920,1080],[1366,768],[1366,600],[390,844],[844,390]]){await p.setViewportSize({width:w,height:h});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(w>=1100)assert(await p.evaluate(()=>document.documentElement.scrollHeight<=innerHeight));const slots=await p.locator('#chips .chip-slot').evaluateAll(es=>es.map(e=>{const b=e.getBoundingClientRect(),chip=e.querySelector('.chip-element')?.getBoundingClientRect();return chip?Math.abs((b.x+b.width/2)-(chip.x+chip.width/2)):0;}));assert(slots.every(d=>d<1),'chip not centered');await shot(p,'table-'+w);}
await p.setViewportSize({width:1366,height:768});for(const [open,dialog,close]of [['#help','#help-dialog','#close-help'],['#edit-build','#build-dialog','#close-build'],['#relic-slots button:first-child','#relic-dialog','#close-relics']]){await p.locator(open).click();for(const width of [1366,390]){await p.setViewportSize({width,height:width===390?844:768});await fit(p,dialog);await shot(p,dialog.slice(1)+'-'+width);}await p.locator(close).click();await p.setViewportSize({width:1366,height:768});}
await p.locator('#open-menu').click();for(const [open,dialog,close]of [['#open-records','#records-dialog','#close-records'],['#open-collection','#collection-dialog','#close-collection'],['#start-run','#restart-dialog','#cancel-restart']]){await p.locator(open).click();await fit(p,dialog);await p.locator(close).click();}await p.context().close();
const tool=g.createState(()=>0);tool.items=[{id:0,name:'Duplicate'},{id:1,name:'Clone'}];tool.nextItemId=2;p=await page(tool);await p.locator('#resume-run').click();await p.locator('#items button').first().click();await p.locator('#wheel-fields [data-index="1"]').click();assert.match(await p.locator('#workbench-preview').innerText(),/19 → 20/);assert(!(await p.locator('#apply-item').isDisabled()));for(const width of [1366,390]){await p.setViewportSize({width,height:width===390?844:768});await fit(p,'#workshop-dialog');await shot(p,'workshop-'+width);}await p.locator('#apply-item').click();assert.equal((await saved(p)).wheel.length,20);await p.reload();await p.locator('#resume-run').click();assert.equal((await saved(p)).items.length,1);await p.context().close();
const shop=g.createState(()=>0);Object.assign(shop,{phase:'map',mapStep:1,currentRoom:'table-2',coins:14,visited:['entry','table-2']});g.enterRoom(shop,'shop',()=>0);p=await page(shop);await p.locator('#resume-run').click();assert.equal(await p.locator('.goods-card').count(),4);await p.locator('.goods-card').nth(1).click();for(const width of [1366,390]){await p.setViewportSize({width,height:width===390?844:768});await fit(p,'#room-dialog');await shot(p,'shop-'+width);}await p.setViewportSize({width:1366,height:768});await p.emulateMedia({reducedMotion:'no-preference'});await p.locator('#purchase-offer').click();await p.locator('#token-dialog').waitFor({state:'visible'});assert(await p.locator('#close-tokens').isDisabled());const pending=(await saved(p)).pendingToken;assert(pending);assert.equal((await saved(p)).tokens.length,0);assert.equal((await saved(p)).coins,6);await p.reload();await p.locator('#resume-run').click();assert.deepEqual((await saved(p)).pendingToken,pending);await p.setViewportSize({width:390,height:844});await fit(p,'#token-dialog');await shot(p,'slot-mobile');await p.locator('#claim-token').click();assert.equal((await saved(p)).chips.length,2);assert(await p.locator('#room-dialog').isVisible());await p.getByRole('button',{name:'ZUR MAP →',exact:true}).click();await fit(p,'#map-dialog');await shot(p,'map-mobile');await p.setViewportSize({width:1366,height:768});await shot(p,'map-desktop');await p.context().close();
// A fully expanded wheel must keep fields distinct and the desktop action reachable.
const dense=g.createState(()=>0);dense.wheel=[...dense.wheel,...dense.wheel];dense.items=[{id:0,name:'Rewrite'}];dense.nextItemId=1;p=await page(dense);await p.locator('#resume-run').click();await p.locator('#items button').first().click();for(const [width,height]of [[1366,600],[1366,768],[390,844]]){await p.setViewportSize({width,height});await fit(p,'#workshop-dialog');if(width>700){const boxes=await p.locator('#wheel-fields button').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};}));for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];assert(!(a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y),'wheel fields overlap');}assert(await p.locator('#apply-item').evaluate(e=>{const r=e.getBoundingClientRect();return r.bottom<=innerHeight&&r.top>=0;}));}await shot(p,'workshop-full-'+width+'-'+height);}await p.locator('#wheel-fields button').first().click();await p.locator('#rewrite-number').fill('7');await p.locator('#apply-item').click();assert.equal((await saved(p)).wheel[0].number,7);await p.context().close();
// End-to-end route traversal uses actual saved edges, not a hard-coded path.
const run=g.createState(()=>.81);run.chips=[0,1,2].map(id=>g.createChip(g.CHIP_CATALOG.find(c=>c.name==='Royal'),id));run.nextChipId=3;p=await page(run);await p.locator('#resume-run').click();
let guard=0;while(guard++<90){const s=await saved(p);if(s.floor===6)break;if(s.phase==='ready'){for(const c of s.chips.slice(0,3)){if(!s.placedBets.some(b=>b.chip.id===c.id)){await p.locator('#chips [data-chip="'+c.id+'"]').click();await p.getByRole('button',{name:'Auf Zahl 1 setzen',exact:true}).click();}}await p.locator('#spin').click();await p.waitForFunction(()=>!document.querySelector('#spin').disabled);}
else if(s.phase==='won'){if(await p.locator('#room-receipt').isVisible())await p.locator('#receipt-continue').click();else await p.locator('#spin').click();}else if(s.phase==='map'){const room=s.map.flat().find(n=>n.id===s.currentRoom);await p.locator('[data-room="'+room.next[0]+'"]').click();}else if(s.phase==='shop')await p.getByRole('button',{name:'ZUR MAP →',exact:true}).click();else if(s.phase==='workshop')await p.getByRole('button',{name:'Ohne Werkzeug weiter →',exact:true}).click();else if(s.phase==='event'){const e=g.EVENTS.find(e=>e.id===s.eventId);if(e.choices)await p.getByRole('button',{name:'OHNE HANDEL WEITER →',exact:true}).click();else await p.getByRole('button',{name:new RegExp(e.safeLabel)}).click();}else if(s.phase==='floor-clear')await p.getByRole('button',{name:new RegExp('FLOOR '+(s.floor+1)+' BETRETEN')}).click();else if(s.phase==='complete')await p.getByRole('button',{name:'CONTINUE · ENDLESS →',exact:true}).click();else throw Error('Unexpected phase '+s.phase);}
assert.equal((await saved(p)).floor,6);await p.reload();await p.locator('#resume-run').click();assert.equal((await saved(p)).floor,6);assert.deepEqual(errors,[]);await browser.close();console.log('PASS menu/table/dialogs PC/mobile, centered chip slots, workshop preview and application, immediate paid slot + reload during animation, random route through all floors and Endless, no JS errors');})().catch(e=>{console.error(e);process.exit(1)});
