const passDetour=require('./route.fixture.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),g=require('../script.js');
const roundTrip=s=>{const decoded=g.decodeRun(g.encodeRun(s,g.normalizeProgress(null),g.normalizeRecords(null)));assert(decoded.ok,JSON.stringify({phase:s.phase,room:s.currentRoom,decoded}));return decoded.state;};
function win(s){for(const c of s.chips.slice(0,3))g.placeBet(s,c.id,'number',1);while(s.phase==='ready'){g.startSpin(s);g.resolveSpin(s,{number:1,color:'red'},()=>1);}assert.equal(s.phase,'won');roundTrip(s);g.nextRound(s);roundTrip(s);}
test('Saved bets reconnect to canonical chips and preserve all mutations/streak',()=>{const s=g.createState(()=>0);s.chips=[g.createChip(g.CHIP_TYPES[5],0)];s.chips[0].streak=4;s.chips[0].mutations=['Lucky','Polished'];g.updateBuildStats(s);g.placeBet(s,0,'number',1);const restored=roundTrip(s);assert.equal(restored.placedBets[0].chip,restored.chips[0]);assert.equal(restored.chips[0].streak,4);g.startSpin(restored);g.resolveSpin(restored,{number:1,color:'red'});assert.equal(restored.chips[0].streak,5);});
test('Shop, fixed event and pending token survive round trips without reroll or duplicate grant',()=>{const s=g.createState(()=>0);win(s);g.enterRoom(s,'stakes');win(s);g.enterRoom(s,'shop',()=>0);g.buyOffer(s,1,null,()=>.2);const outcome=s.pendingToken.name;let loaded=roundTrip(s);assert(loaded.shopOffers[1].sold);assert(!g.buyOffer(loaded,1).ok);loaded=roundTrip(loaded);assert.equal(loaded.pendingToken.name,outcome);assert(g.claimToken(loaded).ok);assert(!g.claimToken(loaded).ok);g.resolveRoom(loaded,'leave');g.enterRoom(loaded,'unknown',()=>2.1/g.EVENTS.length);const restored=roundTrip(loaded);assert.equal(restored.eventId,'envelope');});
test('All floors, boss wheel, victory, Endless and defeat are restorable',()=>{const s=g.createState(()=>0);s.chips=[0,1,2].map(id=>g.createChip(g.CHIP_CATALOG.find(c=>c.name==='Royal'),id));s.nextChipId=3;for(let floor=1;floor<=5;floor++){roundTrip(s);win(s);const p=floor===1?'':'f'+floor+'-';for(const id of (floor===4?['stakes','final-shop','boss']:['table-2','shop','table-3','final-shop','boss'])){if(id==='final-shop')passDetour(s);assert(g.enterRoom(s,p+id,()=>0));roundTrip(s);if(s.phase==='shop'){g.resolveRoom(s,'leave');roundTrip(s);}else win(s);}if(floor===4){assert(g.continueEndless(s,()=>0));}else assert(g.advanceFloor(s,()=>0));}s.spinsLeft=1;g.placeBet(s,0,'number',2);g.startSpin(s);g.resolveSpin(s,{number:1,color:'red'});assert.equal(roundTrip(s).phase,'lost');});
test('Malformed data, unknown versions, invalid bets and unresolved spins are rejected',()=>{const s=g.createState(()=>0);assert(!g.decodeRun('{bad').ok);assert.equal(g.decodeRun('{"version":999}').reason,'version');for(const mutate of [v=>v.state.chips[0].name='injected',v=>v.state.map[0][0].next=['boss'],v=>v.state.wheel=[],v=>v.state.phase='spinning',v=>v.state.chips[0].mutations=['invalid']]){const data=JSON.parse(g.encodeRun(s,null,null));mutate(data);assert(!g.decodeRun(JSON.stringify(data)).ok);}g.placeBet(s,0,'number',1);g.startSpin(s);assert.throws(()=>g.encodeRun(s,null,null));});
test('Recovery merges meta and records without reducing newer achievements',()=>{const a={version:1,redWins:5,numberHits:{1:3},houseVictory:false},b={version:1,redWins:2,numberHits:{1:1,7:2},houseVictory:true};const p=g.mergeProgress(a,b);assert.deepEqual(p.unlocks,['red-five','same-three','house-win']);assert.equal(p.numberHits[7],2);assert.equal(g.mergeRecords({version:1,bestSpin:900},{version:1,bestSpin:30}).bestSpin,900);});
