const {test}=require('node:test');const assert=require('node:assert/strict');const g=require('../script.js');
const seq=(...values)=>()=>values.shift()??0;
function tokenState(name='Slot Token'){const s=g.createState();s.tokens=[{id:0,name}];s.nextTokenId=1;return s;}
test('Rarity weights stay normalized, higher Luck moves weight upward and caps at ten',()=>{assert.deepEqual(g.rarityWeights(0),[60,25,10,4,1]);assert.deepEqual(g.rarityWeights(1),[58,25,11,4.7,1.3]);for(let luck=0;luck<=20;luck++){const weights=g.rarityWeights(luck);assert(Math.abs(weights.reduce((a,b)=>a+b,0)-100)<1e-9);assert(weights.every(n=>n>=0));}assert.deepEqual(g.rarityWeights(99),g.rarityWeights(10));});
test('Standard token category weights and fixed types select the intended pool',()=>{const s=g.createState();for(const [draw,type]of [[0,'chip'],[.55,'relic'],[.8,'item']])assert.equal(g.rollTokenReward(s,'Slot Token',seq(draw,0,0)).type,type);assert.equal(g.rollTokenReward(s,'Chip Token',seq(0,0)).name,'Basic');assert.equal(g.rollTokenReward(s,'Relic Token',seq(0,0)).name,'Blood Pact');});
test('Empty legendary pools downgrade explicitly and owned relics are excluded',()=>{const s=g.createState();const result=g.rollTokenReward(s,'Slot Token',seq(.9,.999,0));assert.equal(result.rolledRarity,'Legendary');assert.equal(result.rarity,'Epic');assert.equal(result.name,'Mitosis');assert(result.fallback);s.relics=[{id:0,name:'Blood Pact'}];assert.equal(g.rollTokenReward(s,'Relic Token',seq(0,0)).name,'Night Market');});
test('Luck changes token rarity but does not edit the wheel',()=>{const s=g.createState();const original=JSON.stringify(s.wheel);assert.equal(g.rollTokenReward(s,'Chip Token',seq(.59,0)).rarity,'Common');s.chips[0].mutations=['Lucky'];g.updateBuildStats(s);assert.equal(g.rollTokenReward(s,'Chip Token',seq(.59,0)).rarity,'Uncommon');assert.equal(JSON.stringify(s.wheel),original);});
test('Token purchase enforces money, pouch capacity and sold-out state',()=>{const s=g.createState();s.phase='shop';s.coins=30;s.shopOffers=Array.from({length:4},()=>({type:'token',name:'Slot Token',price:6,sold:false}));for(let i=0;i<3;i++)assert(g.buyOffer(s,i).ok);assert.equal(s.coins,12);const before=JSON.stringify(s);assert(!g.buyOffer(s,3).ok);assert.equal(JSON.stringify(s),before);assert(!g.buyOffer(s,0).ok);assert.equal(new Set(s.tokens.map(t=>t.id)).size,3);});
test('Token rolls once, blocks duplicate consumption, claims exactly once and restores phase',()=>{const s=tokenState();let rolls=0;assert(g.beginToken(s,0,()=>{rolls++;return 0;}).ok);assert.equal(rolls,5);assert.equal(s.tokens.length,0);assert.equal(s.phase,'slot');const before=JSON.stringify(s);assert(!g.beginToken(s,0,()=>{throw Error('must not roll')}).ok);assert.equal(JSON.stringify(s),before);assert(g.claimToken(s).ok);assert.equal(s.chips.length,2);assert.equal(s.phase,'ready');assert.equal(s.pendingToken,null);assert(!g.claimToken(s).ok);});
test('Full inventory retains pending outcome until explicit replacement or discard',()=>{const s=tokenState('Chip Token');s.chips=g.CHIP_TYPES.map(g.createChip);s.nextChipId=6;g.beginToken(s,0,()=>0);const pending=JSON.stringify(s.pendingToken);assert(!g.claimToken(s).ok);assert.equal(JSON.stringify(s.pendingToken),pending);assert(g.claimToken(s,1).ok);assert.equal(s.chips.length,6);assert.equal(s.chips[1].name,'Basic');s.tokens=[{id:1,name:'Relic Token'}];s.phase='shop';g.beginToken(s,1,()=>0);assert(g.discardToken(s));assert.equal(s.phase,'shop');assert.equal(s.relics.length,0);assert(!g.discardToken(s));});
test('Placed bets and spinning cannot consume tokens; empty pool preserves token',()=>{const s=tokenState();g.placeBet(s,0,'outside','red');assert(!g.beginToken(s,0).ok);g.startSpin(s);assert(!g.beginToken(s,0).ok);assert.equal(s.tokens.length,1);const empty=tokenState('Relic Token');empty.relics=Object.keys(g.RELIC_TYPES).map((name,id)=>({name,id}));assert(!g.beginToken(empty,0).ok);assert.equal(empty.tokens.length,1);});



test('Rare preattached mutations are fixed at reveal and never purchased',()=>{assert(!g.TOKEN_TYPES['Mutation Token']);assert(!g.TOKEN_POOLS.some(o=>o.type==='mutation'));assert.deepEqual(g.createState().chips[0].mutations,[]);for(let i=0;i<4;i++){const s=tokenState('Chip Token');g.beginToken(s,0,seq(0,0,.099,i/4));const name=Object.keys(g.MUTATIONS)[i];assert.deepEqual(s.pendingToken.mutations,[name]);assert(g.claimToken(s).ok);assert.deepEqual(s.chips[1].mutations,[name]);assert.equal(s.capacity,name==='Expanded'?7:6);assert.equal(s.luck,name==='Lucky'?1:0);}assert.deepEqual(g.rollTokenReward(g.createState(),'Chip Token',seq(0,0,.1)).mutations,[]);});
